package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;


/**
 * AppInfo generated by MyEclipse - Hibernate Tools
 */

public class  AppInfo  implements java.io.Serializable {


    // Fields    

     private Long appId;
     private String appName;
     private String appChname;
     private String appDescribe;
     private String appStatusInfo;
     private Long needUserPwd;
     private Long needIpValid;
     private Long needOprSrvRight;
     private Long flowThreshold;
     private Long endUsrFlowThreshold;
     private Long needWseeSign;
     
     private AppFunCateg appFunctionCateg;
     private AppStatus appStatus;
     
  	private java.sql.Blob classContent;
     
     
     private Set srvInfos = new HashSet();
     private Set clientApps = new HashSet();
     private Set appSrvs = new HashSet();
    // Constructors

    /** default constructor */
    public AppInfo() {
    }

	/** minimal constructor */
    public AppInfo(String appName) {
        this.appName = appName;
    }
    
    //用于组装树形菜单
    public AppInfo(Long appId, String appName) {
        this.appId = appId;
        this.appName = appName;
    }
    
    //用于组装树形菜单
    public AppInfo(Long appId, String appName, AppStatus appStatus,  AppFunCateg appFunctionCateg) {
        this.appId = appId;
        this.appName = appName;
        this.appStatus = appStatus;
        this.appFunctionCateg = appFunctionCateg;
    }
    
    /** full constructor */
    public AppInfo(String appName, String appDescribe) {
        this.appName = appName;
        this.appDescribe = appDescribe;
    }
   
    // Property accessors

    public Long getAppId() {
        return this.appId;
    }
    
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppDescribe() {
        return this.appDescribe;
    }
    
    public void setAppDescribe(String appDescribe) {
        this.appDescribe = appDescribe;
    }

	public AppStatus getAppStatus() {
		return appStatus;
	}

	public void setAppStatus(AppStatus appStatus) {
		this.appStatus = appStatus;
	}

	public Set getSrvInfos() {
		return srvInfos;
	}

	public void setSrvInfos(Set srvInfos) {
		this.srvInfos = srvInfos;
	}

	public String getAppStatusInfo() {
		return appStatusInfo;
	}

	public void setAppStatusInfo(String appStatusInfo) {
		this.appStatusInfo = appStatusInfo;
	}

	public AppFunCateg getAppFunctionCateg() {
		return appFunctionCateg;
	}

	public void setAppFunctionCateg(AppFunCateg appFunctionCateg) {
		this.appFunctionCateg = appFunctionCateg;
	}

	public void setNeedUserPwd(Long needUserPwd) {
		this.needUserPwd = needUserPwd;
	}

	public void setNeedIpValid(Long needIpValid) {
		this.needIpValid = needIpValid;
	}

	public Long getNeedUserPwd() {
		return needUserPwd;
	}

	public Long getNeedIpValid() {
		return needIpValid;
	}

	public Set getClientApps() {
		return clientApps;
	}

	public void setClientApps(Set clientApps) {
		this.clientApps = clientApps;
	}

	public Long getFlowThreshold() {
		return flowThreshold;
	}

	public void setFlowThreshold(Long flowThreshold) {
		this.flowThreshold = flowThreshold;
	}

	public Long getEndUsrFlowThreshold() {
		return endUsrFlowThreshold;
	}

	public void setEndUsrFlowThreshold(Long endUsrFlowThreshold) {
		this.endUsrFlowThreshold = endUsrFlowThreshold;
	}

	public Long getNeedOprSrvRight() {
		return needOprSrvRight;
	}

	public void setNeedOprSrvRight(Long needOprSrvRight) {
		this.needOprSrvRight = needOprSrvRight;
	}

	public String getAppChname() {
		return appChname;
	}

	public void setAppChname(String appChname) {
		this.appChname = appChname;
	}

	public Long getNeedWseeSign() {
		return needWseeSign;
	}

	public void setNeedWseeSign(Long needWseeSign) {
		this.needWseeSign = needWseeSign;
	}

	public Set getAppSrvs() {
		return appSrvs;
	}

	public void setAppSrvs(Set appSrvs) {
		this.appSrvs = appSrvs;
	}

	public java.sql.Blob getClassContent() {
		return classContent;
	}

	public void setClassContent(java.sql.Blob classContent) {
		this.classContent = classContent;
	}
   
	







}