package com.sitech.esb.hb;



/**
 * AppStatus generated by MyEclipse - Hibernate Tools
 */

public class  AppStatus  implements java.io.Serializable {


    // Fields    

     private Long appStatusId;
     private String appStatus;


    // Constructors

    /** default constructor */
    public  AppStatus() {
    }

    
    /** full constructor */
    public  AppStatus(String appStatus) {
        this.appStatus = appStatus;
    }

   
    // Property accessors

    public Long getAppStatusId() {
        return this.appStatusId;
    }
    
    public void setAppStatusId(Long appStatusId) {
        this.appStatusId = appStatusId;
    }

    public String getAppStatus() {
        return this.appStatus;
    }
    
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus;
    }
   








}