package com.sitech.esb.hb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * ClientAddr generated by MyEclipse - Hibernate Tools
 */

public class  ClientAddr  implements java.io.Serializable {


    // Fields    

     private Long ipId;
     private ClientInfo clientInfo;
     private String ipAddr;
     private Long validFlag;
   	 private Date monitorBegintime;
	 private Date monitorEndtime;   
	 private Long monitorPeriod;

	 //add by liangpenga 20100703
	 private Set userIps = new HashSet(0) ;

    // Constructors



	public Date getMonitorBegintime() {
		return monitorBegintime;
	}


	public void setMonitorBegintime(Date monitorBegintime) {
		this.monitorBegintime = monitorBegintime;
	}


	public Date getMonitorEndtime() {
		return monitorEndtime;
	}


	public void setMonitorEndtime(Date monitorEndtime) {
		this.monitorEndtime = monitorEndtime;
	}


	public Long getMonitorPeriod() {
		return monitorPeriod;
	}


	public void setMonitorPeriod(Long monitorPeriod) {
		this.monitorPeriod = monitorPeriod;
	}


	/** default constructor */
    public  ClientAddr() {
    }

    
    /** full constructor */
    public  ClientAddr(ClientInfo clientInfo, String ipAddr, Long validFlag) {
        this.clientInfo = clientInfo;
        this.ipAddr = ipAddr;
        this.validFlag = validFlag;
    }

   
    // Property accessors

    public Long getIpId() {
        return this.ipId;
    }
    
    public void setIpId(Long ipId) {
        this.ipId = ipId;
    }

    public String getIpAddr() {
        return this.ipAddr;
    }
    
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }


	public ClientInfo getClientInfo() {
		return clientInfo;
	}


	public void setClientInfo(ClientInfo clientInfo) {
		this.clientInfo = clientInfo;
	}


	public Set getUserIps() {
		return userIps;
	}


	public void setUserIps(Set userIps) {
		this.userIps = userIps;
	}

}