package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;



/**
 * CommProtl generated by MyEclipse - Hibernate Tools
 */

public class  CommProtl  implements java.io.Serializable {


    // Fields    

     private Long commId;
     private String commName;
     private Long commFlag;
     private Set srvCommProtls = new HashSet();


    // Constructors

    /** default constructor */
    public CommProtl() {
    }

    
    /** full constructor */
    public CommProtl(String commName, Long commFlag) {
        this.commName = commName;
        this.commFlag = commFlag;
    }

   
    // Property accessors

    public Long getCommId() {
        return this.commId;
    }
    
    public void setCommId(Long commId) {
        this.commId = commId;
    }

    public String getCommName() {
        return this.commName;
    }
    
    public void setCommName(String commName) {
        this.commName = commName;
    }

    public Long getCommFlag() {
        return this.commFlag;
    }
    
    public void setCommFlag(Long commFlag) {
        this.commFlag = commFlag;
    }


	public Set getSrvCommProtls() {
		return srvCommProtls;
	}


	public void setSrvCommProtls(Set srvCommProtls) {
		this.srvCommProtls = srvCommProtls;
	}

}