package com.sitech.esb.hb;

import java.sql.Blob;

/**
 * EjbRefClass generated by MyEclipse Persistence Tools
 */

public class EjbRefClass implements java.io.Serializable {

	// Fields

	private Long refClassId;
	private String refClassName;
	private String refClassSrc;
	private Blob refClassContent;
	
	private SrvInfo srvInfo;

	// Constructors

	public SrvInfo getSrvInfo() {
		return srvInfo;
	}

	public void setSrvInfo(SrvInfo srvInfo) {
		this.srvInfo = srvInfo;
	}

	/** default constructor */
	public EjbRefClass() {
	}

	/** minimal constructor */
	public EjbRefClass(String refClassName, String refClassSrc) {
		this.refClassName = refClassName;
		this.refClassSrc = refClassSrc;
	}

	/** full constructor */
	public EjbRefClass( String refClassName, String refClassSrc,
			Blob refClassContent) {
		this.refClassName = refClassName;
		this.refClassSrc = refClassSrc;
		this.refClassContent = refClassContent;
	}

	// Property accessors

	public Long getRefClassId() {
		return this.refClassId;
	}

	public void setRefClassId(Long refClassId) {
		this.refClassId = refClassId;
	}

	public String getRefClassName() {
		return this.refClassName;
	}

	public void setRefClassName(String refClassName) {
		this.refClassName = refClassName;
	}

	public String getRefClassSrc() {
		return this.refClassSrc;
	}

	public void setRefClassSrc(String refClassSrc) {
		this.refClassSrc = refClassSrc;
	}

	public Blob getRefClassContent() {
		return this.refClassContent;
	}

	public void setRefClassContent(Blob refClassContent) {
		this.refClassContent = refClassContent;
	}

}