package com.sitech.esb.hb;

/**
 * EsbcltMvRuploadId generated by MyEclipse Persistence Tools
 */

public class EsbcltMvRuploadId implements java.io.Serializable {

	// Fields

	private Long esbcltDldirId;
	private Long esbcltUldirId;

	// Constructors

	/** default constructor */
	public EsbcltMvRuploadId() {
	}

	/** full constructor */
	public EsbcltMvRuploadId(Long esbcltDldirId, Long esbcltUldirId) {
		this.esbcltDldirId = esbcltDldirId;
		this.esbcltUldirId = esbcltUldirId;
	}

	// Property accessors

	public Long getEsbcltDldirId() {
		return this.esbcltDldirId;
	}

	public void setEsbcltDldirId(Long esbcltDldirId) {
		this.esbcltDldirId = esbcltDldirId;
	}

	public Long getEsbcltUldirId() {
		return this.esbcltUldirId;
	}

	public void setEsbcltUldirId(Long esbcltUldirId) {
		this.esbcltUldirId = esbcltUldirId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EsbcltMvRuploadId))
			return false;
		EsbcltMvRuploadId castOther = (EsbcltMvRuploadId) other;

		return ((this.getEsbcltDldirId() == castOther.getEsbcltDldirId()) || (this
				.getEsbcltDldirId() != null
				&& castOther.getEsbcltDldirId() != null && this
				.getEsbcltDldirId().equals(castOther.getEsbcltDldirId())))
				&& ((this.getEsbcltUldirId() == castOther.getEsbcltUldirId()) || (this
						.getEsbcltUldirId() != null
						&& castOther.getEsbcltUldirId() != null && this
						.getEsbcltUldirId()
						.equals(castOther.getEsbcltUldirId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEsbcltDldirId() == null ? 0 : this.getEsbcltDldirId()
						.hashCode());
		result = 37
				* result
				+ (getEsbcltUldirId() == null ? 0 : this.getEsbcltUldirId()
						.hashCode());
		return result;
	}

}