package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;


/**
 * EsbcltDownloadDir generated by MyEclipse Persistence Tools
 */

public class EsbcltDownloadDir  implements java.io.Serializable {


    // Fields    

     private Long esbcltDldirId;
     private FtpServer ftpServer;
     private String remoteDirPath;
     private String localDirPath;
     private String fileNameMatch;
     private Long validFlag;
     private Long scanPeriod;
     private Long isRmSfile;
     private String describle;
     private Set esbcltMvLdownloads = new HashSet(0);
     private Set esbcltMvRuploads = new HashSet(0);

    // Constructors

    public Set getEsbcltMvRuploads() {
		return esbcltMvRuploads;
	}

	public void setEsbcltMvRuploads(Set esbcltMvRUploads) {
		this.esbcltMvRuploads = esbcltMvRUploads;
	}

	/** default constructor */
    public EsbcltDownloadDir() {
    }

	/** minimal constructor */
    public EsbcltDownloadDir(FtpServer ftpServer, String remoteDirPath, String localDirPath, String fileNameMatch, Long validFlag, Long scanPeriod, Long isRmSfile) {
        this.ftpServer = ftpServer;
        this.remoteDirPath = remoteDirPath;
        this.localDirPath = localDirPath;
        this.fileNameMatch = fileNameMatch;
        this.validFlag = validFlag;
        this.scanPeriod = scanPeriod;
        this.isRmSfile = isRmSfile;
    }
    
    /** full constructor */
    public EsbcltDownloadDir(FtpServer ftpServer, String remoteDirPath, String localDirPath, String fileNameMatch, Long validFlag, Long scanPeriod, Long isRmSfile, String describle, Set esbcltMvLdownloads) {
        this.ftpServer = ftpServer;
        this.remoteDirPath = remoteDirPath;
        this.localDirPath = localDirPath;
        this.fileNameMatch = fileNameMatch;
        this.validFlag = validFlag;
        this.scanPeriod = scanPeriod;
        this.isRmSfile = isRmSfile;
        this.describle = describle;
        this.esbcltMvLdownloads = esbcltMvLdownloads;
    }
    public EsbcltDownloadDir(FtpServer ftpServer, String remoteDirPath, String localDirPath, String fileNameMatch, Long validFlag, Long scanPeriod, Long isRmSfile, String describle) {
        this.ftpServer = ftpServer;
        this.remoteDirPath = remoteDirPath;
        this.localDirPath = localDirPath;
        this.fileNameMatch = fileNameMatch;
        this.validFlag = validFlag;
        this.scanPeriod = scanPeriod;
        this.isRmSfile = isRmSfile;
        this.describle = describle;
        this.scanPeriod = scanPeriod;
    }
   
    // Property accessors

    public Long getEsbcltDldirId() {
        return this.esbcltDldirId;
    }
    
    public void setEsbcltDldirId(Long esbcltDldirId) {
        this.esbcltDldirId = esbcltDldirId;
    }

    public FtpServer getFtpServer() {
        return this.ftpServer;
    }
    
    public void setFtpServer(FtpServer ftpServer) {
        this.ftpServer = ftpServer;
    }

    public String getRemoteDirPath() {
        return this.remoteDirPath;
    }
    
    public void setRemoteDirPath(String remoteDirPath) {
        this.remoteDirPath = remoteDirPath;
    }

    public String getLocalDirPath() {
        return this.localDirPath;
    }
    
    public void setLocalDirPath(String localDirPath) {
        this.localDirPath = localDirPath;
    }

    public String getFileNameMatch() {
        return this.fileNameMatch;
    }
    
    public void setFileNameMatch(String fileNameMatch) {
        this.fileNameMatch = fileNameMatch;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }

    public Long getScanPeriod() {
        return this.scanPeriod;
    }
    
    public void setScanPeriod(Long scanPeriod) {
        this.scanPeriod = scanPeriod;
    }

    public Long getIsRmSfile() {
        return this.isRmSfile;
    }
    
    public void setIsRmSfile(Long isRmSfile) {
        this.isRmSfile = isRmSfile;
    }

    public String getDescrible() {
        return this.describle;
    }
    
    public void setDescrible(String describle) {
        this.describle = describle;
    }

    public Set getEsbcltMvLdownloads() {
        return this.esbcltMvLdownloads;
    }
    
    public void setEsbcltMvLdownloads(Set esbcltMvLdownloads) {
        this.esbcltMvLdownloads = esbcltMvLdownloads;
    }
   








}