package com.sitech.esb.hb;



/**
 * EsbcltMvLdownloadId generated by MyEclipse Persistence Tools
 */

public class EsbcltMvLdownloadId  implements java.io.Serializable {


    // Fields    

     private Long esbcltDldirId;
     private Long esbsrvDldirId;


    // Constructors

    /** default constructor */
    public EsbcltMvLdownloadId() {
    }

    
    /** full constructor */
    public EsbcltMvLdownloadId(Long esbcltDldirId, Long esbsrvDldirId) {
        this.esbcltDldirId = esbcltDldirId;
        this.esbsrvDldirId = esbsrvDldirId;
    }

   
    // Property accessors

    public Long getEsbcltDldirId() {
        return this.esbcltDldirId;
    }
    
    public void setEsbcltDldirId(Long esbcltDldirId) {
        this.esbcltDldirId = esbcltDldirId;
    }

    public Long getEsbsrvDldirId() {
        return this.esbsrvDldirId;
    }
    
    public void setEsbsrvDldirId(Long esbsrvDldirId) {
        this.esbsrvDldirId = esbsrvDldirId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EsbcltMvLdownloadId) ) return false;
		 EsbcltMvLdownloadId castOther = ( EsbcltMvLdownloadId ) other; 
         
		 return ( (this.getEsbcltDldirId()==castOther.getEsbcltDldirId()) || ( this.getEsbcltDldirId()!=null && castOther.getEsbcltDldirId()!=null && this.getEsbcltDldirId().equals(castOther.getEsbcltDldirId()) ) )
 && ( (this.getEsbsrvDldirId()==castOther.getEsbsrvDldirId()) || ( this.getEsbsrvDldirId()!=null && castOther.getEsbsrvDldirId()!=null && this.getEsbsrvDldirId().equals(castOther.getEsbsrvDldirId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEsbcltDldirId() == null ? 0 : this.getEsbcltDldirId().hashCode() );
         result = 37 * result + ( getEsbsrvDldirId() == null ? 0 : this.getEsbsrvDldirId().hashCode() );
         return result;
   }   





}