package com.sitech.esb.hb;



/**
 * EsbcltMvLdownload generated by MyEclipse Persistence Tools
 */

public class EsbcltMvLdownload implements java.io.Serializable {


    // Fields    

     private EsbcltMvLdownloadId id;
     private EsbsrvDownloadDir esbsrvDownloadDir;
     private EsbcltDownloadDir esbcltDownloadDir;
     private Long validFlag;


    // Constructors

    /** default constructor */
    public EsbcltMvLdownload() {
    }

    public EsbcltMvLdownload(EsbcltMvLdownloadId id, Long validFlag){
    	this.id = id;
    	this.validFlag = validFlag;
    }
    /** full constructor */
    public EsbcltMvLdownload(EsbcltMvLdownloadId id, EsbsrvDownloadDir esbsrvDownloadDir, EsbcltDownloadDir esbcltDownloadDir, Long validFlag) {
        this.id = id;
        this.esbsrvDownloadDir = esbsrvDownloadDir;
        this.esbcltDownloadDir = esbcltDownloadDir;
        this.validFlag = validFlag;
    }

   
    // Property accessors

    public EsbcltMvLdownloadId getId() {
        return this.id;
    }
    
    public void setId(EsbcltMvLdownloadId id) {
        this.id = id;
    }

    public EsbsrvDownloadDir getEsbsrvDownloadDir() {
        return this.esbsrvDownloadDir;
    }
    
    public void setEsbsrvDownloadDir(EsbsrvDownloadDir esbsrvDownloadDir) {
        this.esbsrvDownloadDir = esbsrvDownloadDir;
    }

    public EsbcltDownloadDir getEsbcltDownloadDir() {
        return this.esbcltDownloadDir;
    }
    
    public void setEsbcltDownloadDir(EsbcltDownloadDir esbcltDownloadDir) {
        this.esbcltDownloadDir = esbcltDownloadDir;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }
   








}