package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;


/**
 * EsbsrvUploadDir generated by MyEclipse Persistence Tools
 */

public class EsbsrvUploadDir  implements java.io.Serializable {


    // Fields    

     private Long esbsrvUldirId;
     private ClientInfo clientInfo;
     private String localDirPath;
     private Long clientId;
     private Long validFlag;
     private String describle;
     private Set esbsrvMvRuploads = new HashSet(0);
     private Set movetoLocalDownlads = new HashSet(0);

     private int maxLoginNumber;
     private int  maxLoginPerip;
     private int downLoadrate;
     private int uploadRate;
     private int idLetime;
     private int writePermission;
    // Constructors
     private Long isSftp;
    public int getMaxLoginNumber() {
		return maxLoginNumber;
	}
	public void setMaxLoginNumber(int maxLoginNumber) {
		this.maxLoginNumber = maxLoginNumber;
	}
	public int getMaxLoginPerip() {
		return maxLoginPerip;
	}
	public void setMaxLoginPerip(int maxLoginPerip) {
		this.maxLoginPerip = maxLoginPerip;
	}
	public int getDownLoadrate() {
		return downLoadrate;
	}
	public void setDownLoadrate(int downLoadrate) {
		this.downLoadrate = downLoadrate;
	}
	public int getUploadRate() {
		return uploadRate;
	}
	public void setUploadRate(int uploadRate) {
		this.uploadRate = uploadRate;
	}
	public int getIdLetime() {
		return idLetime;
	}
	public void setIdLetime(int idLetime) {
		this.idLetime = idLetime;
	}
	public int getWritePermission() {
		return writePermission;
	}
	public void setWritePermission(int writePermission) {
		this.writePermission = writePermission;
	}
	/** default constructor */
    public EsbsrvUploadDir() {
    }
    public EsbsrvUploadDir(ClientInfo client,String localDirPath,Long isSftp,Long validFlag,String describle){
    	this.clientInfo = client;
    	this.localDirPath = localDirPath;
    	this.isSftp = isSftp;
    	this.validFlag = validFlag;
    	this.describle = describle;
    }
	/** minimal constructor */
    public EsbsrvUploadDir(ClientInfo clientInfo, String localDirPath, Long isSftp, Long validFlag) {
        this.clientInfo = clientInfo;
        this.localDirPath = localDirPath;
        this.isSftp = isSftp;
        this.validFlag = validFlag;
    }
    
    /** full constructor */
    public EsbsrvUploadDir(ClientInfo clientInfo, String localDirPath, Long isSftp, Long validFlag, String describle, Set esbsrvMvRuploads, Set movetoLocalDownlads) {
        this.clientInfo = clientInfo;
        this.localDirPath = localDirPath;
        this.isSftp = isSftp;
        this.validFlag = validFlag;
        this.describle = describle;
        this.esbsrvMvRuploads = esbsrvMvRuploads;
        this.movetoLocalDownlads = movetoLocalDownlads;
    }

   
    // Property accessors

    public Long getEsbsrvUldirId() {
        return this.esbsrvUldirId;
    }
    
    public void setEsbsrvUldirId(Long esbsrvUldirId) {
        this.esbsrvUldirId = esbsrvUldirId;
    }

    public ClientInfo getClientInfo() {
        return this.clientInfo;
    }
    
    public void setClientInfo(ClientInfo clientInfo) {
        this.clientInfo = clientInfo;
    }

    public String getLocalDirPath() {
        return this.localDirPath;
    }
    
    public void setLocalDirPath(String localDirPath) {
        this.localDirPath = localDirPath;
    }

    public Long getIsSftp() {
        return this.isSftp;
    }
    
    public void setIsSftp(Long isSftp) {
        this.isSftp = isSftp;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }

    public String getDescrible() {
        return this.describle;
    }
    
    public void setDescrible(String describle) {
        this.describle = describle;
    }

    public Set getEsbsrvMvRuploads() {
        return this.esbsrvMvRuploads;
    }
    
    public void setEsbsrvMvRuploads(Set esbsrvMvRuploads) {
        this.esbsrvMvRuploads = esbsrvMvRuploads;
    }

    public Set getMovetoLocalDownlads() {
        return this.movetoLocalDownlads;
    }
    
    public void setMovetoLocalDownlads(Set movetoLocalDownlads) {
        this.movetoLocalDownlads = movetoLocalDownlads;
    }
	public Long getClientId() {
		return clientId;
	}
	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}
   








}