package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;


/**
 * EsbsrvDownloadDir generated by MyEclipse Persistence Tools
 */

public class EsbsrvDownloadDir  implements java.io.Serializable {


    // Fields    

     private Long esbsrvDldirId;
     private ClientInfo clientInfo;
     private String localDirPath;
     private Long isSftp;
     private Long validFlag;
     private Long isRmSfile;
     private String describle;
     private Set esbcltMvLdownloads = new HashSet(0);
     private Set movetoLocalDownlads = new HashSet(0);


    // Constructors

    /** default constructor */
    public EsbsrvDownloadDir() {
    }

	/** minimal constructor */
    public EsbsrvDownloadDir(ClientInfo clientInfo, String localDirPath, Long isSftp, Long validFlag, Long isRmSfile) {
        this.clientInfo = clientInfo;
        this.localDirPath = localDirPath;
        this.isSftp = isSftp;
        this.validFlag = validFlag;
        this.isRmSfile = isRmSfile;
    }
    public EsbsrvDownloadDir(ClientInfo client,String localDirPath,Long isSftp,Long validFlag,Long isRmSFile,String describle){
    	this.clientInfo = client;
    	this.localDirPath = localDirPath;
    	this.isSftp = isSftp;
    	this.validFlag = validFlag;
    	this.isRmSfile = isRmSFile;
    	this.describle = describle;
    }
    /** full constructor */
    public EsbsrvDownloadDir(ClientInfo clientInfo, String localDirPath, Long isSftp, Long validFlag, Long isRmSfile, String describle, Set esbcltMvLdownloads, Set movetoLocalDownlads) {
        this.clientInfo = clientInfo;
        this.localDirPath = localDirPath;
        this.isSftp = isSftp;
        this.validFlag = validFlag;
        this.isRmSfile = isRmSfile;
        this.describle = describle;
        this.esbcltMvLdownloads = esbcltMvLdownloads;
        this.movetoLocalDownlads = movetoLocalDownlads;
    }

   
    // Property accessors

    public Long getEsbsrvDldirId() {
        return this.esbsrvDldirId;
    }
    
    public void setEsbsrvDldirId(Long esbsrvDldirId) {
        this.esbsrvDldirId = esbsrvDldirId;
    }

    public ClientInfo getClientInfo() {
        return this.clientInfo;
    }
    
    public void setClientInfo(ClientInfo clientInfo) {
        this.clientInfo = clientInfo;
    }

    public String getLocalDirPath() {
        return this.localDirPath;
    }
    
    public void setLocalDirPath(String localDirPath) {
        this.localDirPath = localDirPath;
    }

    public Long getIsSftp() {
        return this.isSftp;
    }
    
    public void setIsSftp(Long isSftp) {
        this.isSftp = isSftp;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }

    public Long getIsRmSfile() {
        return this.isRmSfile;
    }
    
    public void setIsRmSfile(Long isRmSfile) {
        this.isRmSfile = isRmSfile;
    }

    public String getDescrible() {
        return this.describle;
    }
    
    public void setDescrible(String describle) {
        this.describle = describle;
    }

    public Set getEsbcltMvLdownloads() {
        return this.esbcltMvLdownloads;
    }
    
    public void setEsbcltMvLdownloads(Set esbcltMvLdownloads) {
        this.esbcltMvLdownloads = esbcltMvLdownloads;
    }

    public Set getMovetoLocalDownlads() {
        return this.movetoLocalDownlads;
    }
    
    public void setMovetoLocalDownlads(Set movetoLocalDownlads) {
        this.movetoLocalDownlads = movetoLocalDownlads;
    }
   








}