package com.sitech.esb.hb;

// Generated by MyEclipse Persistence Tools

/**
 * EventSrv generated by MyEclipse Persistence Tools
 */
public class EventSrv implements java.io.Serializable {

	// Fields

	private EventSrvId id;
	private Long subsrvOrder;
	private EventConsumer eventConsumer;
	private SrvInfo srvInfo;

	// Constructors

	public SrvInfo getSrvInfo() {
		return srvInfo;
	}

	public void setSrvInfo(SrvInfo srvInfo) {
		this.srvInfo = srvInfo;
	}


	// Property accessors

	public EventSrvId getId() {
		return this.id;
	}

	public void setId(EventSrvId id) {
		this.id = id;
	}

	public Long getSubsrvOrder() {
		return this.subsrvOrder;
	}

	public void setSubsrvOrder(Long subsrvOrder) {
		this.subsrvOrder = subsrvOrder;
	}

	public EventConsumer getEventConsumer() {
		return eventConsumer;
	}

	public void setEventConsumer(EventConsumer eventConsumer) {
		this.eventConsumer = eventConsumer;
	}


}
