package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;

// default package



/**
 * EventConsumer generated by MyEclipse Persistence Tools
 */

public class  EventConsumer  implements java.io.Serializable {


    // Fields    

     private Long eventConsumerId;
     private EventProducer eventProducer;
     private String topicName;
     private String topciChname;
     private String notifyMsgName;
     private Long processMethod;
     private String processLogic;
     private Long validFlag;
     private String describle;
     private String nameSpace;
     private Long logicUpdated;
     private String publicTips;
     private Set srvRs = new HashSet(0);
     private Set eventGens = new HashSet(0);


    // Constructors

    public Set getEventGens() {
		return eventGens;
	}

	public void setEventGens(Set eventGens) {
		this.eventGens = eventGens;
	}

	

	public Set getSrvRs() {
		return srvRs;
	}

	public void setSrvRs(Set srvRs) {
		this.srvRs = srvRs;
	}

	/** default constructor */
    public EventConsumer() {
    }

	/** minimal constructor */
    public EventConsumer(EventProducer eventProducer, String topicName, String topciChname, Long processMethod, String processLogic, Long validFlag) {
        this.eventProducer = eventProducer;
        this.topicName = topicName;
        this.topciChname = topciChname;
        this.processMethod = processMethod;
        this.processLogic = processLogic;
        this.validFlag = validFlag;
    }
    
    /** full constructor */
    public EventConsumer(EventProducer eventProducer, String topicName, String topciChname, String notifyMsgName, Long processMethod, String processLogic, Long validFlag, String describle, String nameSpace,Long logicUpdated,String publicTips,Set srvs,Set eventGens) {
        this.eventProducer = eventProducer;
        this.topicName = topicName;
        this.topciChname = topciChname;
        this.notifyMsgName = notifyMsgName;
        this.processMethod = processMethod;
        this.processLogic = processLogic;
        this.validFlag = validFlag;
        this.describle = describle;
        this.nameSpace = nameSpace;
        this.srvRs = srvs;
        this.publicTips = publicTips;
        this.logicUpdated = logicUpdated;
    }

   
    // Property accessors

    public Long getLogicUpdated() {
		return logicUpdated;
	}

	public void setLogicUpdated(Long logicUpdated) {
		this.logicUpdated = logicUpdated;
	}

	public String getPublicTips() {
		return publicTips;
	}

	public void setPublicTips(String publicTips) {
		this.publicTips = publicTips;
	}

	public Long getEventConsumerId() {
        return this.eventConsumerId;
    }
    
    public void setEventConsumerId(Long eventConsumerId) {
        this.eventConsumerId = eventConsumerId;
    }

    public EventProducer getEventProducer() {
        return this.eventProducer;
    }
    
    public void setEventProducer(EventProducer eventProducer) {
        this.eventProducer = eventProducer;
    }

    public String getTopicName() {
        return this.topicName;
    }
    
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public String getTopciChname() {
        return this.topciChname;
    }
    
    public void setTopciChname(String topciChname) {
        this.topciChname = topciChname;
    }

    public String getNotifyMsgName() {
        return this.notifyMsgName;
    }
    
    public void setNotifyMsgName(String notifyMsgName) {
        this.notifyMsgName = notifyMsgName;
    }

    public Long getProcessMethod() {
        return this.processMethod;
    }
    
    public void setProcessMethod(Long processMethod) {
        this.processMethod = processMethod;
    }

    public String getProcessLogic() {
        return this.processLogic;
    }
    
    public void setProcessLogic(String processLogic) {
        this.processLogic = processLogic;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }

    public String getDescrible() {
        return this.describle;
    }
    
    public void setDescrible(String describle) {
        this.describle = describle;
    }

    public String getNameSpace() {
        return this.nameSpace;
    }
    
    public void setNameSpace(String nameSpace) {
        this.nameSpace = nameSpace;
    }
   








}