package com.sitech.esb.hb;

/**
 * EventSrvId generated by MyEclipse Persistence Tools
 */

public class  EventSrvId implements java.io.Serializable {

	// Fields

	private Long eventConsumerId;
	private Long srvId;

	// Constructors

	/** default constructor */
	public EventSrvId() {
	}

	/** full constructor */
	public EventSrvId(Long eventConsumerId, Long srvId) {
		this.eventConsumerId = eventConsumerId;
		this.srvId = srvId;
	}

	// Property accessors

	public Long getEventConsumerId() {
		return this.eventConsumerId;
	}

	public void setEventConsumerId(Long eventConsumerId) {
		this.eventConsumerId = eventConsumerId;
	}

	public Long getSrvId() {
		return this.srvId;
	}

	public void setSrvId(Long srvId) {
		this.srvId = srvId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventSrvId))
			return false;
		EventSrvId castOther = (EventSrvId) other;

		return ((this.getEventConsumerId() == castOther.getEventConsumerId()) || (this
				.getEventConsumerId() != null
				&& castOther.getEventConsumerId() != null && this
				.getEventConsumerId().equals(castOther.getEventConsumerId())))
				&& ((this.getSrvId() == castOther.getSrvId()) || (this
						.getSrvId() != null
						&& castOther.getSrvId() != null && this.getSrvId()
						.equals(castOther.getSrvId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEventConsumerId() == null ? 0 : this.getEventConsumerId()
						.hashCode());
		result = 37 * result
				+ (getSrvId() == null ? 0 : this.getSrvId().hashCode());
		return result;
	}

}