package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;


/**
 * FtpServer generated by MyEclipse Persistence Tools
 */

public class FtpServer  implements java.io.Serializable {


    // Fields    

     private Long ftpServerId;
     private String ftpServerName;
     private String ftpUser;
     private String ftpPwd;
     private Long isSftp;
     private String ftpIpAddr;
     private Long ftpPort;
     private Long validFlag;
     private String ftpServerDesc;
     private Set esbcltUploadDirs = new HashSet(0);
     private Set esbcltDownloadDirs = new HashSet(0);


    // Constructors

    /** default constructor */
    public FtpServer() {
    }

    public FtpServer(Long id){
    	this.ftpServerId = id;
    }
	/** minimal constructor */
    public FtpServer(String ftpServerName, String ftpUser, String ftpPwd, Long isSftp, String ftpIpAddr, Long ftpPort, Long validFlag) {
        this.ftpServerName = ftpServerName;
        this.ftpUser = ftpUser;
        this.ftpPwd = ftpPwd;
        this.isSftp = isSftp;
        this.ftpIpAddr = ftpIpAddr;
        this.ftpPort = ftpPort;
        this.validFlag = validFlag;
    }
    
    /** full constructor */
    public FtpServer(String ftpServerName, String ftpUser, String ftpPwd, Long isSftp, String ftpIpAddr, Long ftpPort, Long validFlag, String ftpServerDesc, Set esbcltUploadDirs, Set esbcltDownloadDirs) {
        this.ftpServerName = ftpServerName;
        this.ftpUser = ftpUser;
        this.ftpPwd = ftpPwd;
        this.isSftp = isSftp;
        this.ftpIpAddr = ftpIpAddr;
        this.ftpPort = ftpPort;
        this.validFlag = validFlag;
        this.ftpServerDesc = ftpServerDesc;
        this.esbcltUploadDirs = esbcltUploadDirs;
        this.esbcltDownloadDirs = esbcltDownloadDirs;
    }
    public FtpServer(String ftpServerName, String ftpUser, String ftpPwd, Long isSftp, String ftpIpAddr, Long ftpPort, Long validFlag, String ftpServerDesc) {
        this.ftpServerName = ftpServerName;
        this.ftpUser = ftpUser;
        this.ftpPwd = ftpPwd;
        this.isSftp = isSftp;
        this.ftpIpAddr = ftpIpAddr;
        this.ftpPort = ftpPort;
        this.validFlag = validFlag;
        this.ftpServerDesc = ftpServerDesc;
    }
   
    // Property accessors

    public Long getFtpServerId() {
        return this.ftpServerId;
    }
    
    public void setFtpServerId(Long ftpServerId) {
        this.ftpServerId = ftpServerId;
    }

    public String getFtpServerName() {
        return this.ftpServerName;
    }
    
    public void setFtpServerName(String ftpServerName) {
        this.ftpServerName = ftpServerName;
    }

    public String getFtpUser() {
        return this.ftpUser;
    }
    
    public void setFtpUser(String ftpUser) {
        this.ftpUser = ftpUser;
    }

    public String getFtpPwd() {
        return this.ftpPwd;
    }
    
    public void setFtpPwd(String ftpPwd) {
        this.ftpPwd = ftpPwd;
    }

    public Long getIsSftp() {
        return this.isSftp;
    }
    
    public void setIsSftp(Long isSftp) {
        this.isSftp = isSftp;
    }

    public String getFtpIpAddr() {
        return this.ftpIpAddr;
    }
    
    public void setFtpIpAddr(String ftpIpAddr) {
        this.ftpIpAddr = ftpIpAddr;
    }

    public Long getFtpPort() {
        return this.ftpPort;
    }
    
    public void setFtpPort(Long ftpPort) {
        this.ftpPort = ftpPort;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }

    public String getFtpServerDesc() {
        return this.ftpServerDesc;
    }
    
    public void setFtpServerDesc(String ftpServerDesc) {
        this.ftpServerDesc = ftpServerDesc;
    }

    public Set getEsbcltUploadDirs() {
        return this.esbcltUploadDirs;
    }
    
    public void setEsbcltUploadDirs(Set esbcltUploadDirs) {
        this.esbcltUploadDirs = esbcltUploadDirs;
    }

    public Set getEsbcltDownloadDirs() {
        return this.esbcltDownloadDirs;
    }
    
    public void setEsbcltDownloadDirs(Set esbcltDownloadDirs) {
        this.esbcltDownloadDirs = esbcltDownloadDirs;
    }
   








}