package com.sitech.esb.hb;

/**
 * JmsSrvinfo generated by MyEclipse Persistence Tools
 */

public class JmsSrvinfo extends SrvInfo implements
		java.io.Serializable {

	// Fields

	private Long srvId;


	private String jmsServerUrl;

	private Long isConfirmed;

	private String jmsUser;

	private String jmsPwd;

	private Long msgDestType;

	private String msgConfMode;

	private String msgType;

	private String msgDestName;

	private Long prodOrCons;

	private String jmsconf1;

	private String jmsconf2;

	// Constructors

	/** default constructor */
	public JmsSrvinfo() {
	}

	/** minimal constructor */
	public JmsSrvinfo(String jmsServerUrl,
			Long isConfirmed, String jmsUser, String jmsPwd, Long msgDestType,
			String msgConfMode, String msgType, String msgDestName,
			Long prodOrCons) {
		this.jmsServerUrl = jmsServerUrl;
		this.isConfirmed = isConfirmed;
		this.jmsUser = jmsUser;
		this.jmsPwd = jmsPwd;
		this.msgDestType = msgDestType;
		this.msgConfMode = msgConfMode;
		this.msgType = msgType;
		this.msgDestName = msgDestName;
		this.prodOrCons = prodOrCons;
	}

	/** full constructor */
	public JmsSrvinfo(String jmsServerUrl,
			Long isConfirmed, String jmsUser, String jmsPwd, Long msgDestType,
			String msgConfMode, String msgType, String msgDestName,
			Long prodOrCons, String jmsconf1, String jmsconf2) {
		this.jmsServerUrl = jmsServerUrl;
		this.isConfirmed = isConfirmed;
		this.jmsUser = jmsUser;
		this.jmsPwd = jmsPwd;
		this.msgDestType = msgDestType;
		this.msgConfMode = msgConfMode;
		this.msgType = msgType;
		this.msgDestName = msgDestName;
		this.prodOrCons = prodOrCons;
		this.jmsconf1 = jmsconf1;
		this.jmsconf2 = jmsconf2;
	}

	// Property accessors

	public Long getSrvId() {
		return this.srvId;
	}

	public void setSrvId(Long srvId) {
		this.srvId = srvId;
	}

	public String getJmsServerUrl() {
		return this.jmsServerUrl;
	}

	public void setJmsServerUrl(String jmsServerUrl) {
		this.jmsServerUrl = jmsServerUrl;
	}

	public Long getIsConfirmed() {
		return this.isConfirmed;
	}

	public void setIsConfirmed(Long isConfirmed) {
		this.isConfirmed = isConfirmed;
	}

	public String getJmsUser() {
		return this.jmsUser;
	}

	public void setJmsUser(String jmsUser) {
		this.jmsUser = jmsUser;
	}

	public String getJmsPwd() {
		return this.jmsPwd;
	}

	public void setJmsPwd(String jmsPwd) {
		this.jmsPwd = jmsPwd;
	}

	public Long getMsgDestType() {
		return this.msgDestType;
	}

	public void setMsgDestType(Long msgDestType) {
		this.msgDestType = msgDestType;
	}

	public String getMsgConfMode() {
		return this.msgConfMode;
	}

	public void setMsgConfMode(String msgConfMode) {
		this.msgConfMode = msgConfMode;
	}

	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public String getMsgDestName() {
		return this.msgDestName;
	}

	public void setMsgDestName(String msgDestName) {
		this.msgDestName = msgDestName;
	}

	public Long getProdOrCons() {
		return this.prodOrCons;
	}

	public void setProdOrCons(Long prodOrCons) {
		this.prodOrCons = prodOrCons;
	}

	public String getJmsconf1() {
		return this.jmsconf1;
	}

	public void setJmsconf1(String jmsconf1) {
		this.jmsconf1 = jmsconf1;
	}

	public String getJmsconf2() {
		return this.jmsconf2;
	}

	public void setJmsconf2(String jmsconf2) {
		this.jmsconf2 = jmsconf2;
	}

}