package com.sitech.esb.hb;



/**
 * MovetoLocalDownlad generated by MyEclipse Persistence Tools
 */

public class MovetoLocalDownlad  implements java.io.Serializable {


    // Fields    

     private MovetoLocalDownladId id;
     private EsbsrvUploadDir esbsrvUploadDir;
     private EsbsrvDownloadDir esbsrvDownloadDir;
     private Long validFlag;


    // Constructors

    /** default constructor */
    public MovetoLocalDownlad() {
    }

    public MovetoLocalDownlad(MovetoLocalDownladId id,Long validFlag){
    	this.id = id;
    	this.validFlag = validFlag;
    }
    /** full constructor */
    public MovetoLocalDownlad(MovetoLocalDownladId id, EsbsrvUploadDir esbsrvUploadDir, EsbsrvDownloadDir esbsrvDownloadDir, Long validFlag) {
        this.id = id;
        this.esbsrvUploadDir = esbsrvUploadDir;
        this.esbsrvDownloadDir = esbsrvDownloadDir;
        this.validFlag = validFlag;
    }

   
    // Property accessors

    public MovetoLocalDownladId getId() {
        return this.id;
    }
    
    public void setId(MovetoLocalDownladId id) {
        this.id = id;
    }

    public EsbsrvUploadDir getEsbsrvUploadDir() {
        return this.esbsrvUploadDir;
    }
    
    public void setEsbsrvUploadDir(EsbsrvUploadDir esbsrvUploadDir) {
        this.esbsrvUploadDir = esbsrvUploadDir;
    }

    public EsbsrvDownloadDir getEsbsrvDownloadDir() {
        return this.esbsrvDownloadDir;
    }
    
    public void setEsbsrvDownloadDir(EsbsrvDownloadDir esbsrvDownloadDir) {
        this.esbsrvDownloadDir = esbsrvDownloadDir;
    }

    public Long getValidFlag() {
        return this.validFlag;
    }
    
    public void setValidFlag(Long validFlag) {
        this.validFlag = validFlag;
    }
   








}