package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by MyEclipse Persistence Tools
 */

public class  Role implements java.io.Serializable {

	// Fields

	private Long roleId;

	private String roleName;

	private String roleChname;

	private String describle;
	
	//zhengyq@20120321
    private Set Sysrights = new HashSet();
    private Set users = new HashSet();
    //zhengyq@20120321 end 

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(String roleName, String roleChname) {
		this.roleName = roleName;
		this.roleChname = roleChname;
	}

	/** full constructor */
	public Role(String roleName, String roleChname, String describle) {
		this.roleName = roleName;
		this.roleChname = roleChname;
		this.describle = describle;
	}

	// Property accessors

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleChname() {
		return this.roleChname;
	}

	public void setRoleChname(String roleChname) {
		this.roleChname = roleChname;
	}

	public String getDescrible() {
		return this.describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

	public Set getSysrights() {
		return Sysrights;
	}

	public void setSysrights(Set sysrights) {
		Sysrights = sysrights;
	}

	public Set getUsers() {
		return users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}