package com.sitech.esb.hb;



/**
 * SiTxdSrvInfo generated by MyEclipse - Hibernate Tools
 */

public class SiTxdSrvInfo extends SrvInfo implements java.io.Serializable{


    // Fields    


     private String txdRetNums;
     private String srcServiceName;
    // private Long userIdInputNo;
	 private Long oprIdInputNo;
	 private Long phoneInputNo;
	 private Long regionInputNo;
	 private SiTxdoRouteType siTxdoRouteType;
	 private String routeValueXpath;
	 private TxdoSystem txdoSystem;


    // Constructors

    public Long getPhoneInputNo() {
		return phoneInputNo;
	}

	public void setPhoneInputNo(Long phoneInputNo) {
		this.phoneInputNo = phoneInputNo;
	}

	public Long getRegionInputNo() {
		return regionInputNo;
	}

	public void setRegionInputNo(Long regionInputNo) {
		this.regionInputNo = regionInputNo;
	}

	/** default constructor */
    public SiTxdSrvInfo() {
    }

	/** minimal constructor */
    public SiTxdSrvInfo(String srcServiceName) {
        this.srcServiceName = srcServiceName;
    }
    
    /** full constructor */
    public SiTxdSrvInfo(String srvPreParams, String txdRetNums, String srcServiceName) {
       // this.srvPreParams = srvPreParams;
        this.txdRetNums = txdRetNums;
        this.srcServiceName = srcServiceName;
    }

  //取得服务�?基本信息�?
    public SiTxdSrvInfo(Long srvId, String srvName, String srvChName) {
    	super(srvId, srvName, srvChName);
    }
   
    // Property accessors


    public String getTxdRetNums() {
        return this.txdRetNums;
    }
    
    public void setTxdRetNums(String txdRetNums) {
        this.txdRetNums = txdRetNums;
    }

    public String getSrcServiceName() {
        return this.srcServiceName;
    }
    
    public void setSrcServiceName(String srcServiceName) {
        this.srcServiceName = srcServiceName;
    }



	public Long getOprIdInputNo() {
		return oprIdInputNo;
	}

	public void setOprIdInputNo(Long oprIdInputNo) {
		this.oprIdInputNo = oprIdInputNo;
	}

	public SiTxdoRouteType getSiTxdoRouteType() {
		return siTxdoRouteType;
	}

	public void setSiTxdoRouteType(SiTxdoRouteType siTxdoRouteType) {
		this.siTxdoRouteType = siTxdoRouteType;
	}

	public TxdoSystem getTxdoSystem() {
		return txdoSystem;
	}

	public void setTxdoSystem(TxdoSystem txdoSystem) {
		this.txdoSystem = txdoSystem;
	}

	public String getRouteValueXpath() {
		return routeValueXpath;
	}

	public void setRouteValueXpath(String routeValueXpath) {
		this.routeValueXpath = routeValueXpath;
	}

	
}