package com.sitech.esb.hb;

import java.sql.Clob;



/**
 * SiTxdComSrvInfo generated by MyEclipse - Hibernate Tools
 */

public class SiTxdComSrvInfo extends SrvInfo implements java.io.Serializable {

	// Fields    

	private Clob comLogic;

	// Constructors

	/** default constructor */
	public SiTxdComSrvInfo() {
	}

	// Property accessors

	public Clob getComLogic() {
		return this.comLogic;
	}

	public void setComLogic(Clob comLogic) {
		this.comLogic = comLogic;
	}

}