package com.sitech.esb.hb;

import java.sql.Blob;
import java.sql.Clob;



/**
 * SoapSrvInfo generated by MyEclipse - Hibernate Tools
 */

public class SoapAdapter extends SrvInfo implements java.io.Serializable {


    // Fields    

    private String srcWsdlAddr;
	private String srcWsdl;
	private String srcEndpoint;
	private String srcServiceName;
	private String srcAddress;
	private String srcWsdlVer;
	private String servicesXml;
	private String srvWsdl;

	private String nsTrans;
	private String operationTrans;
	private String reqmsgName;
	private String retmsgName;
	
	private Long isSpNamespace;
	private Long isInputXml;
	private Long isOutputXml;
	private String paramsMap;
	
	private String outXpaths;
	private String filterXpaths;
	
	private SoaphttpSystem soaphttpSystem;
	
	//soap复合服务
	private String srcOperationName;
	private Clob comLogic;

	private Blob rarzip_content;  //rar/zip包内容
	private Long isSwsdlJar;
    // Constructors

    /** default constructor */
    public SoapAdapter() {
    }
    
    //取得服务最基本信息用
    public SoapAdapter(Long srvId, String srvName, String srvChName) {
    	super(srvId, srvName, srvChName);
    }
    
    /** full constructor */
    public SoapAdapter(String srcWsdlAddr, String srcWsdl, String srcEndpoint, String srcServiceName, String srcAddress,String srcWsdlVer) {
        this.srcWsdlAddr = srcWsdlAddr;
        this.srcWsdl = srcWsdl;
        this.srcEndpoint = srcEndpoint;
        this.srcServiceName = srcServiceName;
        this.srcAddress = srcAddress;
        this.srcWsdlVer = srcWsdlVer;
    }

   
    public SoapAdapter(String srcWsdlAddr, String srcWsdl, String srcEndpoint,
			String srcServiceName, String srcAddress, String srcWsdlVer,
			String nsTrans, String operationTrans, String reqmsgName,
			String retmsgName) {
		super();
		this.srcWsdlAddr = srcWsdlAddr;
		this.srcWsdl = srcWsdl;
		this.srcEndpoint = srcEndpoint;
		this.srcServiceName = srcServiceName;
		this.srcAddress = srcAddress;
		this.srcWsdlVer = srcWsdlVer;
		this.nsTrans = nsTrans;
		this.operationTrans = operationTrans;
		this.reqmsgName = reqmsgName;
		this.retmsgName = retmsgName;
	}


	// Property accessors
    public String getSrcWsdlAddr() {
        return this.srcWsdlAddr;
    }
    
    public void setSrcWsdlAddr(String srcWsdlAddr) {
        this.srcWsdlAddr = srcWsdlAddr;
    }

    public String getSrcWsdl() {
        return this.srcWsdl;
    }
    
    public void setSrcWsdl(String srcWsdl) {
        this.srcWsdl = srcWsdl;
    }

    public String getSrcEndpoint() {
        return this.srcEndpoint;
    }
    
    public void setSrcEndpoint(String srcEndpoint) {
        this.srcEndpoint = srcEndpoint;
    }

    public String getSrcServiceName() {
        return this.srcServiceName;
    }
    
    public void setSrcServiceName(String srcServiceName) {
        this.srcServiceName = srcServiceName;
    }

    public String getSrcAddress() {
        return this.srcAddress;
    }
    
    public void setSrcAddress(String srcAddress) {
        this.srcAddress = srcAddress;
    }


	public String getSrcWsdlVer() {
		return srcWsdlVer;
	}


	public void setSrcWsdlVer(String srcWsdlVer) {
		this.srcWsdlVer = srcWsdlVer;
	}


	public String getNsTrans() {
		return nsTrans;
	}


	public void setNsTrans(String nsTrans) {
		this.nsTrans = nsTrans;
	}


	public String getOperationTrans() {
		return operationTrans;
	}


	public void setOperationTrans(String operationTrans) {
		this.operationTrans = operationTrans;
	}


	public String getReqmsgName() {
		return reqmsgName;
	}


	public void setReqmsgName(String reqmsgName) {
		this.reqmsgName = reqmsgName;
	}


	public String getRetmsgName() {
		return retmsgName;
	}


	public void setRetmsgName(String retmsgName) {
		this.retmsgName = retmsgName;
	}


	public Long getIsSpNamespace() {
		return isSpNamespace;
	}


	public void setIsSpNamespace(Long isSpNamespace) {
		this.isSpNamespace = isSpNamespace;
	}


	public Long getIsInputXml() {
		return isInputXml;
	}


	public void setIsInputXml(Long isInputXml) {
		this.isInputXml = isInputXml;
	}


	public Long getIsOutputXml() {
		return isOutputXml;
	}


	public void setIsOutputXml(Long isOutputXml) {
		this.isOutputXml = isOutputXml;
	}


	public String getParamsMap() {
		return paramsMap;
	}


	public void setParamsMap(String paramsMap) {
		this.paramsMap = paramsMap;
	}


	public String getOutXpaths() {
		return outXpaths;
	}


	public void setOutXpaths(String outXpaths) {
		this.outXpaths = outXpaths;
	}


	public String getFilterXpaths() {
		return filterXpaths;
	}


	public void setFilterXpaths(String filterXpaths) {
		this.filterXpaths = filterXpaths;
	}


	public SoaphttpSystem getSoaphttpSystem() {
		return soaphttpSystem;
	}


	public void setSoaphttpSystem(SoaphttpSystem soaphttpSystem) {
		this.soaphttpSystem = soaphttpSystem;
	}

	public String getSrcOperationName() {
		return srcOperationName;
	}

	public void setSrcOperationName(String srcOperationName) {
		this.srcOperationName = srcOperationName;
	}

	public void setComLogic(Clob comLogic) {
		this.comLogic = comLogic;
	}

	public Clob getComLogic() {
		return comLogic;
	}
	public Blob getrarzip_content() {
		return this.rarzip_content;
	}

	public void setrarzip_content(Blob rarzip_content) {
		this.rarzip_content = rarzip_content;
	}
	
	public Long getisSwsdlJar() {
		return isSwsdlJar;
	}

	public void setisSwsdlJar(Long isSwsdlJar) {
		this.isSwsdlJar = isSwsdlJar;
	}

	public String getServicesXml() {
		return servicesXml;
	}

	public void setServicesXml(String servicesXml) {
		this.servicesXml = servicesXml;
	}

	public String getSrvWsdl() {
		return srvWsdl;
	}

	public void setSrvWsdl(String srvWsdl) {
		this.srvWsdl = srvWsdl;
	}
	
	

}