package com.sitech.esb.hb;



/**
 * SrvCommProtl generated by MyEclipse - Hibernate Tools
 */

public class  SrvCommProtl  implements java.io.Serializable {


    // Fields    

     private Long srvCommId;
     private SrvInfo service;
     private CommProtl commProtl;
     private String srvAddr;

    // Constructors

    /** default constructor */
    public SrvCommProtl() {
    }

	/** minimal constructor */
    public SrvCommProtl(SrvInfo service, CommProtl commProtl) {
        this.service = service;
        this.commProtl = commProtl;
    }
    
    /** full constructor */
    public SrvCommProtl(SrvInfo service, CommProtl commProtl, String srvAddr) {
    	this.service = service;
        this.commProtl = commProtl;
        this.srvAddr = srvAddr;
    }
   
    // Property accessors

    public Long getSrvCommId() {
        return this.srvCommId;
    }
    
    public void setSrvCommId(Long srvCommId) {
        this.srvCommId = srvCommId;
    }

	public SrvInfo getService() {
		return service;
	}

	public void setService(SrvInfo service) {
		this.service = service;
	}

	public CommProtl getCommProtl() {
		return commProtl;
	}

	public void setCommProtl(CommProtl commProtl) {
		this.commProtl = commProtl;
	}

	public String getSrvAddr() {
		return srvAddr;
	}

	public void setSrvAddr(String srvAddr) {
		this.srvAddr = srvAddr;
	}
}