package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;



/**
 * SrvCateg generated by MyEclipse - Hibernate Tools
 */

public class  SrvCateg  implements java.io.Serializable {


    // Fields    

     private Long srvCategId;
     private SrvDimension srvDimension;
     private String srvCategName;
     private Set srvInfos = new HashSet();
     
    // Constructors

    /** default constructor */
    public SrvCateg() {
    }

    
    /** full constructor */
    public SrvCateg(SrvDimension srvDimension, String srvCategName) {
    	this.srvDimension = srvDimension;
        this.srvCategName = srvCategName;
    }

   
    // Property accessors

    public Long getSrvCategId() {
        return this.srvCategId;
    }
    
    public void setSrvCategId(Long srvCategId) {
        this.srvCategId = srvCategId;
    }

	public Set getSrvInfos() {
		return srvInfos;
	}


	public void setSrvInfos(Set srvInfos) {
		this.srvInfos = srvInfos;
	}


	public SrvDimension getSrvDimension() {
		return srvDimension;
	}


	public void setSrvDimension(SrvDimension srvDimension) {
		this.srvDimension = srvDimension;
	}


	public String getSrvCategName() {
		return srvCategName;
	}


	public void setSrvCategName(String srvCategName) {
		this.srvCategName = srvCategName;
	}
   








}