package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;



/**
 * SrvDimension generated by MyEclipse - Hibernate Tools
 */

public class  SrvDimension  implements java.io.Serializable {


    // Fields    

     private Long srvDimenId;
     private String srvDimenName;
     
     private Set srvCategs = new HashSet();
     private Set userSrvDimLevels = new HashSet();
     
    // Constructors

    /** default constructor */
    public  SrvDimension() {
    }

    
    /** full constructor */
    public  SrvDimension(String srvDimenName) {
        this.srvDimenName = srvDimenName;
    }

   
    // Property accessors

    public Long getSrvDimenId() {
        return this.srvDimenId;
    }
    
    public void setSrvDimenId(Long srvDimenId) {
        this.srvDimenId = srvDimenId;
    }

    public String getSrvDimenName() {
        return this.srvDimenName;
    }
    
    public void setSrvDimenName(String srvDimenName) {
        this.srvDimenName = srvDimenName;
    }

	public Set getSrvCategs() {
		return srvCategs;
	}


	public void setSrvCategs(Set srvCategs) {
		this.srvCategs = srvCategs;
	}

	public Set getUserSrvDimLevels() {
		return userSrvDimLevels;
	}


	public void setUserSrvDimLevels(Set userSrvDimLevels) {
		this.userSrvDimLevels = userSrvDimLevels;
	}
   








}