package com.sitech.esb.hb;

import java.sql.Blob;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * SrvInfo generated by MyEclipse - Hibernate Tools
 */

public class  SrvInfo implements java.io.Serializable {

	// Fields
	private Long srvWsdlFileid;
	private Long srvId;
	private SrvStatus srvStatus;
	private String srvName;
	private String srvChName;
	private String srvDescribe;
	private String inparamsDemo;
	private String srvVer;
	private String srvModifyTime;
	private Long validFlag;
	private String businessUuid;
	private String srvUuid;
	private SrvType srvType;
	private SrvTimeoutCfg srvTimeoutCfg;
	private String srvPubInfo;
	private String sreqXmlEncoding;
	private String retXmlEncoding;

	private Long needSaveInParam;
	private Long needSaveOutParam;
	private Long isCoreSrv;
	private Long isUnifySrv;
	private Long isneedUpdateuddi;

	//	private Set events = new HashSet();	

	private AppInfo appInfo;
	private Long srvOrder;

	private Set srvInputs = new HashSet();
	private Set srvOutputs = new HashSet();
	private Set srvCommProtls = new HashSet();
	private Set srvCategs = new HashSet();
	private Set srvAccesorys = new HashSet();
	private Set srvErrinfos = new HashSet();


    // ����״̬
	private Integer isolatedState;

	//soap������
	//tuxedo����������һ���ֶ�srcServiceName
	private String srcWsdlAddr;
	private String srcWsdl;
	private String srcEndpoint;
	private String srcAddress;
	private String srcWsdlVer;

	private String nsTrans;
	private String operationTrans;
	private String reqmsgName;
	private String retmsgName;

	private Long isSpNamespace;
	private Long isInputXml;
	private Long isOutputXml;
	private String paramsMap;

	private SoaphttpSystem soaphttpSystem;
	
	//zhengyq@20110201
	private Long isSwsdlJar;
	private Blob rarzip_content;
	//end zhengyq@20110201

	//soap���Ϸ���
	private String srcOperationName;

	//tuxedo�����
	private String srcServiceName;
	private String txdRetNums;
	private Long userIdInputNo;
	private Long oprIdInputNo;
	private Long phoneInputNo;
	private Long regionInputNo;
	private SiTxdoRouteType siTxdoRouteType;
	private TxdoSystem txdoSystem;
	private Long isdumpCoremsg;
	private String routeValueXpath;

	//���Ϸ���
	//���Ϸ���Ҳ��userIdInputNo,oprIdInputNo�����ֶ�
	private Clob comLogic;
	private Clob wsdl;
	private String validateLogic;
	private Long needInparamCheck = new Long(0);

	//sitech Utype web����
	private Clob inXsd;
	private Clob outXsd;
	private Long isCheckOutXsd;
	private String retCodeXpath;
	private String retMsgXpath;
	private String retCodeXpath2;
	private String fixedValues;
	//��xml���������
	private String phoneXpath;
	private String workNoXpath;
	private String regionIdXpath;
	private String usrIdXpath;
	private String custIdXpath;
	private String acctIdXpath;
	private String partitionXpath;
	
	private String outXpaths;
	private String filterXpaths;
	
	//Tuxedo/JSON����
	private Clob inJsd;
	private Clob outJsd;
	private Long isCheck;
	private String retCodeJpath;
	private String retMsgJpath;
	private String retCodeJpath2;
	//��xml���������
	private String phoneJpath;
	private String workNoJpath;
	private String regionIdJpath;
	private String usrIdJpath;
	private String custIdJpath;
	private String acctIdJpath;
	private String partitionJpath;
	
	private String outJpaths;
	private String filterJpaths;

	//Socket�������ֶ�
	private String socketIp;
	private Long socketPort;
	private Long socketType; //zhangqinga@20111212

	//http�������ֶ�
	private String saddress;
	private String reqContentType;
	private String acceptType;
	private String reqCharset;
	private String resCharset;
	private Long reqTimeout;
	private String httpHeaders;
	private String retcodeXpath;
	private String retcodeXpath2;
	private String retmsgXpath;
	private String webType;
	private String postJoinUp;
    private String getJoinUp;
    private String putJoinUp;
    private String deleteJoinUp;
	
	//HSF������, �����ֶ���http����������
	private String zookeeperAppName;
	private String groupName;
	private String protocolType;
	private String loadbalance;
	private String hsfversion;
	

	/*********add by liangpenga 20100707 ***************/
	private Set srvEvent = new HashSet(0);//�����¼��؆�
	private Set eventSrv = new HashSet(0);//�¼����ц�,�����ϵ

	//ejb�������ֆ�
	private String sserviceName;
	private String remoteInterfaceName;
	private String homeInterfaceName;
	private String jndiName;
	private String providerUrl;
	private String contextFactory;
	private String remoteIfsrc;
	private String homeIfsrc;
	private String jndiUser;
	private String jndiPwd;
	private Blob remoteIfcontent;
	private Blob homeIfcontent;
	//	private Long isInputXml;
	//	private Long isOutputXml;
	//	private String retcodeXpath;
	//	private String retcodeXpath2;
	//	private String retmsgXpath;
	//	private String outXpaths;
	//	private String filterXpaths;
	private Blob wraperContent;

	private String ejbVersion;

	//CommonSkelton
	private String serviceCode;
	private Blob res_content;
	private Long isSoap;

	private Set srvRelationsForSrvSubId = new HashSet(0);
	private Set srvRelationsForSrvParentId = new HashSet(0);
	private Set refClasses = new HashSet(0);
	// Constructors

	private Set srvSchemaFiles = new HashSet();
	private Blob srvWsdlFile;
	private String srvWsdlFilenname;
	private Blob srvSchemaFile;
	private String srvSchemaFilename;
	private Long srvSchemaFileId;

	public Long getSrvSchemaFileId() {
		return srvSchemaFileId;
	}

	public void setSrvSchemaFileId(Long srvSchemaFileId) {
		this.srvSchemaFileId = srvSchemaFileId;
	}

	public Blob getSrvSchemaFile() {
		return srvSchemaFile;
	}

	public void setSrvSchemaFile(Blob srvSchemaFile) {
		this.srvSchemaFile = srvSchemaFile;
	}

	public Set getSrvSchemaFiles() {
		return srvSchemaFiles;
	}

	public void setSrvSchemaFiles(Set srvSchemaFiles) {
		this.srvSchemaFiles = srvSchemaFiles;
	}


	//yangzl �������ӷ������ͷ���ʱ	

	/** default constructor */
	public  SrvInfo() {
	}

	public String getSaddress() {
		return saddress;
	}

	public Set getSrvRelationsForSrvSubId() {
		return srvRelationsForSrvSubId;
	}

	public void setSrvRelationsForSrvSubId(Set srvRelationsForSrvSubId) {
		this.srvRelationsForSrvSubId = srvRelationsForSrvSubId;
	}

	public Set getSrvRelationsForSrvParentId() {
		return srvRelationsForSrvParentId;
	}

	public void setSrvRelationsForSrvParentId(Set srvRelationsForSrvParentId) {
		this.srvRelationsForSrvParentId = srvRelationsForSrvParentId;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public String getReqContentType() {
		return reqContentType;
	}

	public void setReqContentType(String reqContentType) {
		this.reqContentType = reqContentType;
	}

	public String getReqCharset() {
		return reqCharset;
	}

	public void setReqCharset(String reqCharset) {
		this.reqCharset = reqCharset;
	}

	public String getResCharset() {
		return resCharset;
	}

	public void setResCharset(String resCharset) {
		this.resCharset = resCharset;
	}

	public Long getReqTimeout() {
		return reqTimeout;
	}

	public void setReqTimeout(Long reqTimeout) {
		this.reqTimeout = reqTimeout;
	}

	public String getHttpHeaders() {
		return httpHeaders;
	}

	public void setHttpHeaders(String httpHeaders) {
		this.httpHeaders = httpHeaders;
	}

	public String getRetcodeXpath() {
		return retcodeXpath;
	}

	public void setRetcodeXpath(String retcodeXpath) {
		this.retcodeXpath = retcodeXpath;
	}

	public String getRetcodeXpath2() {
		return retcodeXpath2;
	}

	public void setRetcodeXpath2(String retcodeXpath2) {
		this.retcodeXpath2 = retcodeXpath2;
	}

	public String getRetmsgXpath() {
		return retmsgXpath;
	}

	public void setRetmsgXpath(String retmsgXpath) {
		this.retmsgXpath = retmsgXpath;
	}

	public String getSocketIp() {
		return socketIp;
	}

	public void setSocketIp(String socketIp) {
		this.socketIp = socketIp;
	}

	public Long getSocketPort() {
		return socketPort;
	}

	public void setSocketPort(Long socketPort) {
		this.socketPort = socketPort;
	}

	//zhangqinga@20111212
	public Long getSocketType() {
		return socketType;
	}

	public void setSocketType(Long socketType) {
		this.socketType = socketType;
	}
	//ended zhangqinga@20111212
	
	
	//������װ���β˵�
	public  SrvInfo(Long srvId, String srvName, String srvChName,
			SrvType srvType) {
		this.srvId = srvId;
		this.srvName = srvName;
		this.srvChName = srvChName;
		this.srvType = srvType;
	}

	//ȡ�÷�����������Ϣ��
	public SrvInfo(Long srvId, String srvName, String srvChName) {
		this.srvId = srvId;
		this.srvName = srvName;
		this.srvChName = srvChName;
	}

	//ȡ�÷�����������Ϣ��
	public SrvInfo(Long srvId, String srvName, String srvChName,
			SrvType srvType, SrvStatus srvStatus) {
		this.srvId = srvId;
		this.srvName = srvName;
		this.srvChName = srvChName;
		this.srvType = srvType;
		this.srvStatus = srvStatus;
	}

	/** minimal constructor */
	public SrvInfo(SrvStatus srvStatus, String srvName,
			String srvChName, String businessUuid, String srvUuid) {
		this.srvStatus = srvStatus;
		this.srvName = srvName;
		this.srvChName = srvChName;
		this.businessUuid = businessUuid;
		this.srvUuid = srvUuid;
	}

	/** full constructor */
	public SrvInfo(SrvStatus srvStatus, String srvName,
			String srvChName, SrvType srvType, String srvDescribe,
			String srvVer, String businessUuid, String srvUuid,
			String inparamsDemo) {
		this.srvStatus = srvStatus;
		this.srvName = srvName;
		this.srvChName = srvChName;
		this.srvType = srvType;
		this.srvDescribe = srvDescribe;
		this.srvVer = srvVer;
		this.businessUuid = businessUuid;
		this.srvUuid = srvUuid;
		this.inparamsDemo = inparamsDemo;
	}

	// Property accessors

	public Long getSrvId() {
		return this.srvId;
	}

	public void setSrvId(Long srvId) {
		this.srvId = srvId;
	}

	public SrvStatus getSrvStatus() {
		return this.srvStatus;
	}

	public void setSrvStatus(SrvStatus srvStatus) {
		this.srvStatus = srvStatus;
	}

	public String getSrvName() {
		return this.srvName;
	}

	public void setSrvName(String srvName) {
		this.srvName = srvName;
	}

	public String getSrvChName() {
		return this.srvChName;
	}

	public void setSrvChName(String srvChName) {
		this.srvChName = srvChName;
	}

	public String getSrvDescribe() {
		return this.srvDescribe;
	}

	public void setSrvDescribe(String srvDescribe) {
		this.srvDescribe = srvDescribe;
	}

	public String getBusinessUuid() {
		return this.businessUuid;
	}

	public void setBusinessUuid(String businessUuid) {
		this.businessUuid = businessUuid;
	}

	public String getSrvUuid() {
		return this.srvUuid;
	}

	public void setSrvUuid(String srvUuid) {
		this.srvUuid = srvUuid;
	}

	public Set getSrvCommProtls() {
		return srvCommProtls;
	}

	public void setSrvCommProtls(Set srvCommProtls) {
		this.srvCommProtls = srvCommProtls;
	}

	public Set getSrvInputs() {
		return srvInputs;
	}

	public void setSrvInputs(Set srvInputs) {
		this.srvInputs = srvInputs;
	}

	public Set getSrvOutputs() {
		return srvOutputs;
	}

	public void setSrvOutputs(Set srvOutputs) {
		this.srvOutputs = srvOutputs;
	}

	public String getSrvPubInfo() {
		return srvPubInfo;
	}

	public void setSrvPubInfo(String srvPubInfo) {
		this.srvPubInfo = srvPubInfo;
	}

	public void setSrvVer(String srvVer) {
		this.srvVer = srvVer;
	}

	public String getSrvVer() {
		return srvVer;
	}

	public SrvType getSrvType() {
		return srvType;
	}

	public void setSrvType(SrvType srvType) {
		this.srvType = srvType;
	}

	public String getSrcAddress() {
		return srcAddress;
	}

	public void setSrcAddress(String srcAddress) {
		this.srcAddress = srcAddress;
	}

	public String getSrcEndpoint() {
		return srcEndpoint;
	}

	public void setSrcEndpoint(String srcEndpoint) {
		this.srcEndpoint = srcEndpoint;
	}

	public String getSrcServiceName() {
		return srcServiceName;
	}

	public void setSrcServiceName(String srcServiceName) {
		this.srcServiceName = srcServiceName;
	}

	public String getSrcWsdl() {
		return srcWsdl;
	}

	public void setSrcWsdl(String srcWsdl) {
		this.srcWsdl = srcWsdl;
	}

	public String getSrcWsdlAddr() {
		return srcWsdlAddr;
	}

	public void setSrcWsdlAddr(String srcWsdlAddr) {
		this.srcWsdlAddr = srcWsdlAddr;
	}

	public String getTxdRetNums() {
		return txdRetNums;
	}

	public void setTxdRetNums(String txdRetNums) {
		this.txdRetNums = txdRetNums;
	}

	public Set getSrvCategs() {
		return srvCategs;
	}

	public void setSrvCategs(Set srvCategs) {
		this.srvCategs = srvCategs;
	}

	public AppInfo getAppInfo() {
		return appInfo;
	}

	public void setAppInfo(AppInfo appInfo) {
		this.appInfo = appInfo;
	}

	public void setSrvOrder(Long srvOrder) {
		this.srvOrder = srvOrder;
	}

	public Long getSrvOrder() {
		return srvOrder;
	}

	public Set getSrvAccesorys() {
		return srvAccesorys;
	}

	public void setSrvAccesorys(Set srvAccesorys) {
		this.srvAccesorys = srvAccesorys;
	}

	//
	//	public Long getUserIdInputNo() {
	//		return userIdInputNo;
	//	}
	//
	//	public void setUserIdInputNo(Long userIdInputNo) {
	//		this.userIdInputNo = userIdInputNo;
	//	}

	public Long getPhoneInputNo() {
		return phoneInputNo;
	}

	public void setPhoneInputNo(Long phoneInputNo) {
		this.phoneInputNo = phoneInputNo;
	}

	public Long getRegionInputNo() {
		return regionInputNo;
	}

	public void setRegionInputNo(Long regionInputNo) {
		this.regionInputNo = regionInputNo;
	}

	public Long getOprIdInputNo() {
		return oprIdInputNo;
	}

	public void setOprIdInputNo(Long oprIdInputNo) {
		this.oprIdInputNo = oprIdInputNo;
	}

	public SiTxdoRouteType getSiTxdoRouteType() {
		return siTxdoRouteType;
	}

	public void setSiTxdoRouteType(SiTxdoRouteType siTxdoRouteType) {
		this.siTxdoRouteType = siTxdoRouteType;
	}

	public Clob getInXsd() {
		return inXsd;
	}

	public void setInXsd(Clob inXsd) {
		this.inXsd = inXsd;
	}

	public Clob getOutXsd() {
		return outXsd;
	}

	public void setOutXsd(Clob outXsd) {
		this.outXsd = outXsd;
	}

	public Long getIsCheckOutXsd() {
		return isCheckOutXsd;
	}

	public void setIsCheckOutXsd(Long isCheckOutXsd) {
		this.isCheckOutXsd = isCheckOutXsd;
	}

	public String getRetCodeXpath() {
		return retCodeXpath;
	}

	public void setRetCodeXpath(String retCodeXpath) {
		this.retCodeXpath = retCodeXpath;
	}

	public String getRetMsgXpath() {
		return retMsgXpath;
	}

	public void setRetMsgXpath(String retMsgXpath) {
		this.retMsgXpath = retMsgXpath;
	}

	public String getRetCodeXpath2() {
		if (null == retCodeXpath2 || "null".equals(retCodeXpath2)) {
			retCodeXpath2 = "";
		}
		return retCodeXpath2;
	}

	public void setRetCodeXpath2(String retCodeXpath2) {
		this.retCodeXpath2 = retCodeXpath2;
	}

	public Set getSrvErrinfos() {
		return srvErrinfos;
	}

	public void setSrvErrinfos(Set srvErrinfos) {
		this.srvErrinfos = srvErrinfos;
	}

	public Clob getComLogic() {
		return comLogic;
	}

	public void setComLogic(Clob comLogic) {
		this.comLogic = comLogic;
	}

	public String getValidateLogic() {
		return validateLogic;
	}

	public void setValidateLogic(String validateLogic) {
		this.validateLogic = validateLogic;
	}

	public TxdoSystem getTxdoSystem() {
		return txdoSystem;
	}

	public void setTxdoSystem(TxdoSystem txdoSystem) {
		this.txdoSystem = txdoSystem;
	}

	public String getSrcWsdlVer() {
		return srcWsdlVer;
	}

	public void setSrcWsdlVer(String srcWsdlVer) {
		this.srcWsdlVer = srcWsdlVer;
	}

	public String getNsTrans() {
		return nsTrans;
	}

	public void setNsTrans(String nsTrans) {
		this.nsTrans = nsTrans;
	}

	public String getOperationTrans() {
		return operationTrans;
	}

	public void setOperationTrans(String operationTrans) {
		this.operationTrans = operationTrans;
	}

	public String getReqmsgName() {
		return reqmsgName;
	}

	public void setReqmsgName(String reqmsgName) {
		this.reqmsgName = reqmsgName;
	}

	public String getRetmsgName() {
		return retmsgName;
	}

	public void setRetmsgName(String retmsgName) {
		this.retmsgName = retmsgName;
	}

	public Long getIsSpNamespace() {
		return isSpNamespace;
	}

	public void setIsSpNamespace(Long isSpNamespace) {
		this.isSpNamespace = isSpNamespace;
	}

	public Long getIsInputXml() {
		return isInputXml;
	}

	public void setIsInputXml(Long isInputXml) {
		this.isInputXml = isInputXml;
	}

	public Long getIsOutputXml() {
		return isOutputXml;
	}

	public void setIsOutputXml(Long isOutputXml) {
		this.isOutputXml = isOutputXml;
	}

	public String getParamsMap() {
		return paramsMap;
	}

	public void setParamsMap(String paramsMap) {
		this.paramsMap = paramsMap;
	}

	public Long getIsdumpCoremsg() {
		return isdumpCoremsg;
	}

	public void setIsdumpCoremsg(Long isdumpCoremsg) {
		this.isdumpCoremsg = isdumpCoremsg;
	}

	public Long getNeedSaveInParam() {
		return needSaveInParam;
	}

	public void setNeedSaveInParam(Long needSaveInParam) {
		this.needSaveInParam = needSaveInParam;
	}

	public String getRegionIdXpath() {
		return regionIdXpath;
	}

	public void setRegionIdXpath(String regionIdXpath) {
		this.regionIdXpath = regionIdXpath;
	}

	public String getCustIdXpath() {
		return custIdXpath;
	}

	public void setCustIdXpath(String custIdXpath) {
		this.custIdXpath = custIdXpath;
	}

	public String getOutXpaths() {
		return outXpaths;
	}

	public void setOutXpaths(String outXpaths) {
		this.outXpaths = outXpaths;
	}

	public String getFilterXpaths() {
		return filterXpaths;
	}

	public void setFilterXpaths(String filterXpaths) {
		this.filterXpaths = filterXpaths;
	}

	public String getPhoneXpath() {
		return phoneXpath;
	}

	public void setPhoneXpath(String phoneXpath) {
		this.phoneXpath = phoneXpath;
	}

	public String getWorkNoXpath() {
		return workNoXpath;
	}

	public void setWorkNoXpath(String workNoXpath) {
		this.workNoXpath = workNoXpath;
	}

	public String getUsrIdXpath() {
		return usrIdXpath;
	}

	public void setUsrIdXpath(String usrIdXpath) {
		this.usrIdXpath = usrIdXpath;
	}

	public String getAcctIdXpath() {
		return acctIdXpath;
	}

	public void setAcctIdXpath(String acctIdXpath) {
		this.acctIdXpath = acctIdXpath;
	}

	public SoaphttpSystem getSoaphttpSystem() {
		return soaphttpSystem;
	}

	public void setSoaphttpSystem(SoaphttpSystem soaphttpSystem) {
		this.soaphttpSystem = soaphttpSystem;
	}

	public String getRetXmlEncoding() {
		return retXmlEncoding;
	}

	public void setRetXmlEncoding(String retXmlEncoding) {
		this.retXmlEncoding = retXmlEncoding;
	}

	public String getSreqXmlEncoding() {
		return sreqXmlEncoding;
	}

	public void setSreqXmlEncoding(String sreqXmlEncoding) {
		this.sreqXmlEncoding = sreqXmlEncoding;
	}

	public String getPartitionXpath() {
		return partitionXpath;
	}

	public void setPartitionXpath(String partitionXpath) {
		this.partitionXpath = partitionXpath;
	}

	public Long getValidFlag() {
		return validFlag;
	}

	public void setValidFlag(Long validFlag) {
		this.validFlag = validFlag;
	}

	public String getSrcOperationName() {
		return srcOperationName;
	}

	public void setSrcOperationName(String srcOperationName) {
		this.srcOperationName = srcOperationName;
	}

	public String getInparamsDemo() {
		return inparamsDemo;
	}

	public void setInparamsDemo(String inparamsDemo) {
		this.inparamsDemo = inparamsDemo;
	}

	public Long getUserIdInputNo() {
		return userIdInputNo;
	}

	public void setUserIdInputNo(Long userIdInputNo) {
		this.userIdInputNo = userIdInputNo;
	}

	public Set getSrvEvent() {
		return srvEvent;
	}

	public void setSrvEvent(Set srvEvent) {
		this.srvEvent = srvEvent;
	}

	public Set getEventSrv() {
		return eventSrv;
	}

	public void setEventSrv(Set eventSrv) {
		this.eventSrv = eventSrv;
	}

	public String getSserviceName() {
		return sserviceName;
	}

	public void setSserviceName(String sserviceName) {
		this.sserviceName = sserviceName;
	}

	public String getRemoteInterfaceName() {
		return remoteInterfaceName;
	}

	public void setRemoteInterfaceName(String remoteInterfaceName) {
		this.remoteInterfaceName = remoteInterfaceName;
	}

	public String getHomeInterfaceName() {
		return homeInterfaceName;
	}

	public void setHomeInterfaceName(String homeInterfaceName) {
		this.homeInterfaceName = homeInterfaceName;
	}

	public String getJndiName() {
		return jndiName;
	}

	public void setJndiName(String jndiName) {
		this.jndiName = jndiName;
	}

	public String getProviderUrl() {
		return providerUrl;
	}

	public void setProviderUrl(String providerUrl) {
		this.providerUrl = providerUrl;
	}

	public String getContextFactory() {
		return contextFactory;
	}

	public void setContextFactory(String contextFactory) {
		this.contextFactory = contextFactory;
	}

	public String getRemoteIfsrc() {
		return remoteIfsrc;
	}

	public void setRemoteIfsrc(String remoteIfsrc) {
		this.remoteIfsrc = remoteIfsrc;
	}

	public String getHomeIfsrc() {
		return homeIfsrc;
	}

	public void setHomeIfsrc(String homeIfsrc) {
		this.homeIfsrc = homeIfsrc;
	}

	public String getJndiUser() {
		return jndiUser;
	}

	public void setJndiUser(String jndiUser) {
		this.jndiUser = jndiUser;
	}

	public String getJndiPwd() {
		return jndiPwd;
	}

	public void setJndiPwd(String jndiPwd) {
		this.jndiPwd = jndiPwd;
	}

	public Blob getRemoteIfcontent() {
		return remoteIfcontent;
	}

	public void setRemoteIfcontent(Blob remoteIfcontent) {
		this.remoteIfcontent = remoteIfcontent;
	}

	public Blob getHomeIfcontent() {
		return homeIfcontent;
	}

	public void setHomeIfcontent(Blob homeIfcontent) {
		this.homeIfcontent = homeIfcontent;
	}

	public Blob getWraperContent() {
		return wraperContent;
	}

	public void setWraperContent(Blob wraperContent) {
		this.wraperContent = wraperContent;
	}

	public String getEjbVersion() {
		return ejbVersion;
	}

	public void setEjbVersion(String ejbVersion) {
		this.ejbVersion = ejbVersion;
	}

	public Set getRefClasses() {
		return refClasses;
	}

	public void setRefClasses(Set refClasses) {
		this.refClasses = refClasses;
	}

	//	public Set getEvents() {
	//		return events;
	//	}
	//
	//	public void setEvents(Set events) {
	//		this.events = events;
	//	}
	// add by sunhx start
	public Long getNeedInparamCheck() {
		return needInparamCheck;
	}

	public void setNeedInparamCheck(Long needInparamCheck) {
		this.needInparamCheck = needInparamCheck;
	}

	// add by sunhx end

	/*public String getTargetWsdl() {
		return targetWsdl;
	}

	public void setTargetWsdl(String targetWsdl) {
		this.targetWsdl = targetWsdl;
	}

	public String getReqXslt() {
		return reqXslt;
	}

	public void setReqXslt(String reqXslt) {
		this.reqXslt = reqXslt;
	}

	public String getRetXslt() {
		return retXslt;
	}

	public void setRetXslt(String retXslt) {
		this.retXslt = retXslt;
	}

	public String getLogicJavaXslt() {
		return logicJavaXslt;
	}

	public void setLogicJavaXslt(String logicJavaXslt) {
		this.logicJavaXslt = logicJavaXslt;
	}

	public String getIsreqstring() {
		return isreqstring;
	}

	public void setIsreqstring(String isreqstring) {
		this.isreqstring = isreqstring;
	}

	public String getIsretstring() {
		return isretstring;
	}

	public void setIsretstring(String isretstring) {
		this.isretstring = isretstring;
	}*/

	public Blob getSrvWsdlFile() {
		return srvWsdlFile;
	}

	public void setSrvWsdlFile(Blob srvWsdlFile) {
		this.srvWsdlFile = srvWsdlFile;
	}

	public SrvTimeoutCfg getSrvTimeoutCfg() {
		return srvTimeoutCfg;
	}

	public void setSrvTimeoutCfg(SrvTimeoutCfg srvTimeoutCfg) {
		this.srvTimeoutCfg = srvTimeoutCfg;
	}

	public String getServiceCode() {
		return serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	public String getSrvWsdlFilenname() {
		return srvWsdlFilenname;
	}

	public void setSrvWsdlFilenname(String srvWsdlFilenname) {
		this.srvWsdlFilenname = srvWsdlFilenname;
	}

	public Long getSrvWsdlFileid() {
		return srvWsdlFileid;
	}

	public void setSrvWsdlFileid(Long srvWsdlFileid) {
		this.srvWsdlFileid = srvWsdlFileid;
	}

	public String getSrvSchemaFilename() {
		return srvSchemaFilename;
	}

	public void setSrvSchemaFilename(String srvSchemaFilename) {
		this.srvSchemaFilename = srvSchemaFilename;
	}

	//JMS
	private String jmsServerUrl;

	private Long isConfirmed;

	private String jmsUser;

	private String jmsPwd;

	private Long msgDestType;

	private String msgConfMode;

	private String msgType;

	private String msgDestName;

	private Long prodOrCons;

	private String jmsconf1;

	private String jmsconf2;

	public String getJmsServerUrl() {
		return this.jmsServerUrl;
	}

	public void setJmsServerUrl(String jmsServerUrl) {
		this.jmsServerUrl = jmsServerUrl;
	}

	public Long getIsConfirmed() {
		return this.isConfirmed;
	}

	public void setIsConfirmed(Long isConfirmed) {
		this.isConfirmed = isConfirmed;
	}

	public String getJmsUser() {
		return this.jmsUser;
	}

	public void setJmsUser(String jmsUser) {
		this.jmsUser = jmsUser;
	}

	public String getJmsPwd() {
		return this.jmsPwd;
	}

	public void setJmsPwd(String jmsPwd) {
		this.jmsPwd = jmsPwd;
	}

	public Long getMsgDestType() {
		return this.msgDestType;
	}

	public void setMsgDestType(Long msgDestType) {
		this.msgDestType = msgDestType;
	}

	public String getMsgConfMode() {
		return this.msgConfMode;
	}

	public void setMsgConfMode(String msgConfMode) {
		this.msgConfMode = msgConfMode;
	}

	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public String getMsgDestName() {
		return this.msgDestName;
	}

	public void setMsgDestName(String msgDestName) {
		this.msgDestName = msgDestName;
	}

	public Long getProdOrCons() {
		return this.prodOrCons;
	}

	public void setProdOrCons(Long prodOrCons) {
		this.prodOrCons = prodOrCons;
	}

	public String getJmsconf1() {
		return this.jmsconf1;
	}

	public void setJmsconf1(String jmsconf1) {
		this.jmsconf1 = jmsconf1;
	}

	public String getJmsconf2() {
		return this.jmsconf2;
	}

	public void setJmsconf2(String jmsconf2) {
		this.jmsconf2 = jmsconf2;
	}

	public Blob getres_content() {
		return this.res_content;
	}

	public void setres_content(Blob res_content) {
		this.res_content = res_content;
	}
	
	public Long getIsSoap() {
		return isSoap;
	}

	public void setIsSoap(Long isSoap) {
		this.isSoap = isSoap;
	}

	public String getFixedValues() {
		return fixedValues;
	}

	public void setFixedValues(String fixedValues) {
		this.fixedValues = fixedValues;
	}
	public String getSrvModifyTime() {
		return srvModifyTime;
	}

	public void setSrvModifyTime(String srvModifyTime) {
		this.srvModifyTime = srvModifyTime;
	}

	public Long getNeedSaveOutParam() {
		return needSaveOutParam;
	}

	public void setNeedSaveOutParam(Long needSaveOutParam) {
		this.needSaveOutParam = needSaveOutParam;
	}

	public Blob getrarzip_content() {
		return this.rarzip_content;
	}

	public void setrarzip_content(Blob rarzip_content) {
		this.rarzip_content = rarzip_content;
	}
	
	public Long getisSwsdlJar() {
		return isSwsdlJar;
	}

	public void setisSwsdlJar(Long isSwsdlJar) {
		this.isSwsdlJar = isSwsdlJar;
	}

	public String getAcceptType() {
		return acceptType;
	}

	public void setAcceptType(String acceptType) {
		this.acceptType = acceptType;
	}

	public Clob getInJsd() {
		return inJsd;
	}

	public void setInJsd(Clob inJsd) {
		this.inJsd = inJsd;
	}

	public Clob getOutJsd() {
		return outJsd;
	}

	public void setOutJsd(Clob outJsd) {
		this.outJsd = outJsd;
	}

	public Long getIsCheck() {
		return isCheck;
	}

	public void setIsCheck(Long isCheck) {
		this.isCheck = isCheck;
	}

	public String getRetCodeJpath() {
		return retCodeJpath;
	}

	public void setRetCodeJpath(String retCodeJpath) {
		this.retCodeJpath = retCodeJpath;
	}

	public String getRetMsgJpath() {
		return retMsgJpath;
	}

	public void setRetMsgJpath(String retMsgJpath) {
		this.retMsgJpath = retMsgJpath;
	}

	public String getRetCodeJpath2() {
		return retCodeJpath2;
	}

	public void setRetCodeJpath2(String retCodeJpath2) {
		this.retCodeJpath2 = retCodeJpath2;
	}

	public String getPhoneJpath() {
		return phoneJpath;
	}

	public void setPhoneJpath(String phoneJpath) {
		this.phoneJpath = phoneJpath;
	}

	public String getWorkNoJpath() {
		return workNoJpath;
	}

	public void setWorkNoJpath(String workNoJpath) {
		this.workNoJpath = workNoJpath;
	}

	public String getRegionIdJpath() {
		return regionIdJpath;
	}

	public void setRegionIdJpath(String regionIdJpath) {
		this.regionIdJpath = regionIdJpath;
	}

	public String getUsrIdJpath() {
		return usrIdJpath;
	}

	public void setUsrIdJpath(String usrIdJpath) {
		this.usrIdJpath = usrIdJpath;
	}

	public String getCustIdJpath() {
		return custIdJpath;
	}

	public void setCustIdJpath(String custIdJpath) {
		this.custIdJpath = custIdJpath;
	}

	public String getAcctIdJpath() {
		return acctIdJpath;
	}

	public void setAcctIdJpath(String acctIdJpath) {
		this.acctIdJpath = acctIdJpath;
	}

	public String getPartitionJpath() {
		return partitionJpath;
	}

	public void setPartitionJpath(String partitionJpath) {
		this.partitionJpath = partitionJpath;
	}

	public String getOutJpaths() {
		return outJpaths;
	}

	public void setOutJpaths(String outJpaths) {
		this.outJpaths = outJpaths;
	}

	public String getFilterJpaths() {
		return filterJpaths;
	}

	public void setFilterJpaths(String filterJpaths) {
		this.filterJpaths = filterJpaths;
	}

	public Long getIsCoreSrv() {
		return isCoreSrv;
	}

	public void setIsCoreSrv(Long isCoreSrv) {
		this.isCoreSrv = isCoreSrv;
	}
	
	public String getWebType() {
		return webType;
	}

	public void setWebType(String webType) {
		this.webType = webType;
	}

	public String getZookeeperAppName() {
		return zookeeperAppName;
	}

	public void setZookeeperAppName(String zookeeperAppName) {
		this.zookeeperAppName = zookeeperAppName;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getProtocolType() {
		return protocolType;
	}

	public void setProtocolType(String protocolType) {
		this.protocolType = protocolType;
	}

	public String getLoadbalance() {
		return loadbalance;
	}

	public void setLoadbalance(String loadbalance) {
		this.loadbalance = loadbalance;
	}

	public String getRouteValueXpath() {
		return routeValueXpath;
	}

	public void setRouteValueXpath(String routeValueXpath) {
		this.routeValueXpath = routeValueXpath;
	}

	public Long getIsUnifySrv() {
		return isUnifySrv;
	}

	public void setIsUnifySrv(Long isUnifySrv) {
		this.isUnifySrv = isUnifySrv;
	}

	public String getHsfversion() {
		return hsfversion;
	}

	public void setHsfversion(String hsfversion) {
		this.hsfversion = hsfversion;
	}
	public Long getIsneedUpdateuddi() {
		return isneedUpdateuddi;
	}

	public void setIsneedUpdateuddi(Long isneedUpdateuddi) {
		this.isneedUpdateuddi = isneedUpdateuddi;
	}

	public Clob getWsdl() {
		return wsdl;
	}

	public void setWsdl(Clob wsdl) {
		this.wsdl = wsdl;
	}

	public Integer getIsolatedState() {
		return isolatedState;
	}

	public void setIsolatedState(Integer isolatedState) {
		this.isolatedState = isolatedState;
	}

	public String getPostJoinUp() {
		return postJoinUp;
	}

	public void setPostJoinUp(String postJoinUp) {
		this.postJoinUp = postJoinUp;
	}

	public String getGetJoinUp() {
		return getJoinUp;
	}

	public void setGetJoinUp(String getJoinUp) {
		this.getJoinUp = getJoinUp;
	}

	public String getPutJoinUp() {
		return putJoinUp;
	}

	public void setPutJoinUp(String putJoinUp) {
		this.putJoinUp = putJoinUp;
	}

	public String getDeleteJoinUp() {
		return deleteJoinUp;
	}

	public void setDeleteJoinUp(String deleteJoinUp) {
		this.deleteJoinUp = deleteJoinUp;
	}
	
}