package com.sitech.esb.hb;



/**
 * SrvType generated by MyEclipse - Hibernate Tools
 */

public class  SrvType  implements java.io.Serializable {


    // Fields    

     private Long srvType;
     private String srvTypeName;
     private String srvTypeDesc;
     private Long validFlag;


    // Constructors

    /** default constructor */
    public  SrvType() {
    }

	/** minimal constructor */
    public  SrvType(String srvTypeName) {
        this.srvTypeName = srvTypeName;
    }
    
    /** full constructor */
    public  SrvType(String srvTypeName, String srvTypeDesc) {
        this.srvTypeName = srvTypeName;
        this.srvTypeDesc = srvTypeDesc;
    }

   
    // Property accessors

    public Long getSrvType() {
        return this.srvType;
    }
    
    public void setSrvType(Long srvType) {
        this.srvType = srvType;
    }

    public String getSrvTypeName() {
        return this.srvTypeName;
    }
    
    public void setSrvTypeName(String srvTypeName) {
        this.srvTypeName = srvTypeName;
    }

    public String getSrvTypeDesc() {
        return this.srvTypeDesc;
    }
    
    public void setSrvTypeDesc(String srvTypeDesc) {
        this.srvTypeDesc = srvTypeDesc;
    }

	public Long getValidFlag() {
		return validFlag;
	}

	public void setValidFlag(Long validFlag) {
		this.validFlag = validFlag;
	}
   








}