package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;

/**
 *  generated by MyEclipse Persistence Tools
 */

public class  Sysright implements java.io.Serializable {

	// Fields

	private Long rightId;

	private String rightName;

	private String rightChname;

	private String describle;
	
	//zhengyq@20120321
    private Set roles = new HashSet();
    //zhengyq@20120321 end 

	// Constructors

	/** default constructor */
	public Sysright() {
	}

	/** minimal constructor */
	public Sysright(String rightName, String rightChname) {
		this.rightName = rightName;
		this.rightChname = rightChname;
	}

	/** full constructor */
	public Sysright(String rightName, String rightChname,
			String describle) {
		this.rightName = rightName;
		this.rightChname = rightChname;
		this.describle = describle;
	}

	// Property accessors

	public Long getRightId() {
		return this.rightId;
	}

	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	public String getRightChname() {
		return this.rightChname;
	}

	public void setRightChname(String rightChname) {
		this.rightChname = rightChname;
	}

	public String getDescrible() {
		return this.describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

	public Set getRoles() {
		return roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}