package com.sitech.esb.hb;



/**
 * SiTongEASY_srvinf generated by MyEclipse - Hibernate Tools
 */

public class TongEASYSrvInfo extends SrvInfo implements java.io.Serializable{


    // Fields    


     private String txdRetNums;
     private String srcServiceName;
	 private Long oprIdInputNo;


    // Constructors

	/** default constructor */
    public TongEASYSrvInfo() {
    }

	/** minimal constructor */
    public TongEASYSrvInfo(String srcServiceName) {
        this.srcServiceName = srcServiceName;
    }
    
    /** full constructor */
    public TongEASYSrvInfo(String srvPreParams, String txdRetNums, String srcServiceName) {
       // this.srvPreParams = srvPreParams;
        this.txdRetNums = txdRetNums;
        this.srcServiceName = srcServiceName;
    }

  //取得服务最基本信息用
    public TongEASYSrvInfo(Long srvId, String srvName, String srvChName) {
    	super(srvId, srvName, srvChName);
    }
   
    // Property accessors


    public String getTxdRetNums() {
        return this.txdRetNums;
    }
    
    public void setTxdRetNums(String txdRetNums) {
        this.txdRetNums = txdRetNums;
    }

    public String getSrcServiceName() {
        return this.srcServiceName;
    }
    
    public void setSrcServiceName(String srcServiceName) {
        this.srcServiceName = srcServiceName;
    }



	public Long getOprIdInputNo() {
		return oprIdInputNo;
	}

	public void setOprIdInputNo(Long oprIdInputNo) {
		this.oprIdInputNo = oprIdInputNo;
	}

}