package com.sitech.esb.hb;

import java.util.HashSet;
import java.util.Set;



/**
 * Userinfo generated by MyEclipse - Hibernate Tools
 */

public class  Userinfo  implements java.io.Serializable {


    // Fields    

     private Long userId;
     private String userName;
     private String userPwd;
     private String userDescribe;
     private Long validFlag; 
     private Long srvLanguage; 
     
     private ClientInfo clientInfo;
     private Set userSrvDimLevels = new HashSet();
     //add by liangpenga 20100702
     private Set userIps = new HashSet();
     
     //zhengyq@20120321
     private Set roles = new HashSet();
     //zhengyq@20120321 end 
     
     private Long isBindIp;
    // Constructors

    public Set getUserIps() {
		return userIps;
	}

	public void setUserIps(Set userIps) {
		this.userIps = userIps;
	}

	/** default constructor */
    public  Userinfo() {
    }

	/** minimal constructor */
    public  Userinfo(String userName, String userPwd) {
        this.userName = userName;
        this.userPwd = userPwd;
    }
    
    /** full constructor */
    public  Userinfo(String userName, String userPwd, String userDescribe) {
        this.userName = userName;
        this.userPwd = userPwd;
        this.userDescribe = userDescribe;
    }

   
    // Property accessors

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    public String getUserDescribe() {
        return this.userDescribe;
    }
    
    public void setUserDescribe(String userDescribe) {
        this.userDescribe = userDescribe;
    }

	public ClientInfo getClientInfo() {
		return clientInfo;
	}

	public void setClientInfo(ClientInfo clientInfo) {
		this.clientInfo = clientInfo;
	}

	public Set getUserSrvDimLevels() {
		return userSrvDimLevels;
	}

	public void setUserSrvDimLevels(Set userSrvDimLevels) {
		this.userSrvDimLevels = userSrvDimLevels;
	}

	public Long getValidFlag() {
		return validFlag;
	}

	public void setValidFlag(Long validFlag) {
		this.validFlag = validFlag;
	}

	public Long getSrvLanguage() {
		return srvLanguage;
	}

	public void setSrvLanguage(Long srvLanguage) {
		this.srvLanguage = srvLanguage;
	}

	public Long getIsBindIp() {
		return isBindIp;
	}

	public void setIsBindIp(Long isBindIp) {
		this.isBindIp = isBindIp;
	}

	public Set getRoles() {
		return roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

   








}