package com.sitech.esb.hb;

/**
 * UserIpId generated by MyEclipse Persistence Tools
 */

public class  UserIpId implements java.io.Serializable {

	// Fields

	private Long userId;
	private Long ipId;

	// Constructors

	/** default constructor */
	public  UserIpId() {
	}

	/** full constructor */
	public  UserIpId(Long userId, Long ipId) {
		this.userId = userId;
		this.ipId = ipId;
	}

	// Property accessors

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getIpId() {
		return this.ipId;
	}

	public void setIpId(Long ipId) {
		this.ipId = ipId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserIpId))
			return false;
		UserIpId castOther = (UserIpId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(
				castOther.getUserId())))
				&& ((this.getIpId() == castOther.getIpId()) || (this.getIpId() != null
						&& castOther.getIpId() != null && this.getIpId()
						.equals(castOther.getIpId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getIpId() == null ? 0 : this.getIpId().hashCode());
		return result;
	}

}