package com.sitech.esb.hb;

/**
 * UserIp generated by MyEclipse Persistence Tools
 */

public class  UserIp implements java.io.Serializable {

	// Fields

	private UserIpId id;
	private Long validFlag;
	
	private Userinfo userInfo;
	private ClientAddr clientAddr;

	// Constructors

	public Userinfo getUserInfo() {
		return userInfo;
	}

	public void setUserInfo(Userinfo userInfo) {
		this.userInfo = userInfo;
	}

	public ClientAddr getClientAddr() {
		return clientAddr;
	}

	public void setClientAddr(ClientAddr clientAddr) {
		this.clientAddr = clientAddr;
	}

	/** default constructor */
	public  UserIp() {
	}

	/** full constructor */
	public  UserIp(UserIpId id, Long validFlag) {
		this.id = id;
		this.validFlag = validFlag;
	}

	// Property accessors

	public UserIpId getId() {
		return this.id;
	}

	public void setId(UserIpId id) {
		this.id = id;
	}

	public Long getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(Long validFlag) {
		this.validFlag = validFlag;
	}

}